// Generated by npm run build:client. Edit src/ui/client/ instead.
window.__ModuleLoader__.load({
  id: 'dsh-feiyufm-core',
  factory: (require) => {
    const React = require('react');
    // src/ui/client/styles.mjs
    // PHL-inspired tokens and timing. Source/provenance: THIRD_PARTY_NOTICES.md.
    const css = `
      .fishfm,.fm-float {
        --fm-canvas:hsl(220 20% 96%); --fm-surface:hsl(0 0% 100%);
        --fm-raised:hsl(0 0% 100%); --fm-sunken:hsl(220 20% 97%);
        --fm-hover:hsl(220 24% 95.5%); --fm-line:hsl(220 16% 90%);
        --fm-line-strong:hsl(220 14% 82%); --fm-ink:hsl(222 30% 13%);
        --fm-muted:hsl(220 10% 38%); --fm-faint:hsl(220 10% 45%);
        --fm-accent:hsl(219 84% 55%); --fm-accent-hover:hsl(219 84% 50%);
        --fm-accent-soft:hsl(219 84% 96%); --fm-accent-ink:hsl(219 74% 42%);
        --fm-on-accent:white; --fm-ok:hsl(152 62% 38%);
        --fm-warn:hsl(33 92% 46%); --fm-danger:hsl(356 70% 51%);
        --fm-shadow:0 8px 28px hsl(222 44% 22% / .08);
        --fm-popup-shadow:0 12px 38px hsl(222 44% 22% / .16);
        --fm-ease:cubic-bezier(.22,.61,.36,1);
        --fm-spring:cubic-bezier(.2,.8,.3,1.15);
        --fm-press:90ms; --fm-fast:160ms; --fm-base:220ms; --fm-page:260ms;
        --fm-sheen:650ms; --fm-motion-shift:6px;
        box-sizing:border-box; color:var(--fm-ink); font-family:inherit; font-size:13px; line-height:1.5;
        color-scheme:light;
      }
      :is([data-ds-dark-theme],.dark,[data-theme=dark]) :is(.fishfm,.fm-float),
      :is(.fishfm,.fm-float)[data-theme=dark] {
        --fm-canvas:hsl(224 18% 8%); --fm-surface:hsl(222 16% 12.5%);
        --fm-raised:hsl(222 15% 15%); --fm-sunken:hsl(224 18% 10%);
        --fm-hover:hsl(222 14% 18%); --fm-line:hsl(222 12% 21%);
        --fm-line-strong:hsl(222 10% 30%); --fm-ink:hsl(220 22% 93%);
        --fm-muted:hsl(220 9% 64%); --fm-faint:hsl(220 8% 56%);
        --fm-accent:hsl(216 88% 62%); --fm-accent-hover:hsl(216 88% 67%);
        --fm-accent-soft:hsl(216 60% 20%); --fm-accent-ink:hsl(216 88% 72%);
        --fm-on-accent:hsl(220 40% 8%); --fm-ok:hsl(152 55% 46%);
        --fm-warn:hsl(36 90% 56%); --fm-danger:hsl(356 72% 60%);
        --fm-shadow:0 8px 28px hsl(224 60% 2% / .2);
        --fm-popup-shadow:0 12px 38px hsl(224 60% 2% / .4); color-scheme:dark;
      }
      :is(.fishfm,.fm-float)[data-motion=reduced] {
        --fm-press:50ms; --fm-fast:88ms; --fm-base:121ms; --fm-page:143ms;
        --fm-sheen:358ms; --fm-motion-shift:2px;
      }
      :is(.fishfm,.fm-float)[data-motion=off] {
        --fm-press:0ms; --fm-fast:0ms; --fm-base:0ms; --fm-page:0ms; --fm-motion-shift:0px;
      }
      :is(.fishfm,.fm-float) * { box-sizing:border-box; }
      :is(.fishfm,.fm-float) button,:is(.fishfm,.fm-float) input,
      :is(.fishfm,.fm-float) select { font:inherit; }
      :is(.fishfm,.fm-float) button { cursor:pointer; }
      :is(.fishfm,.fm-float) button:disabled { opacity:.45; cursor:default; }
      :is(.fishfm,.fm-float) :focus-visible { outline:2px solid var(--fm-accent); outline-offset:3px; }
      .fishfm { container-type:inline-size; container-name:fishfm; width:100%;
        max-width:1120px; margin:auto; padding:24px; background:var(--fm-canvas);
        height:100%; min-height:0; overflow:auto; overscroll-behavior:contain;
        animation:fm-page-in var(--fm-page) var(--fm-ease) both; }
      .fishfm h1,.fishfm h2,.fishfm p { margin:0; }
      .fm-top { display:flex; align-items:flex-start; flex-wrap:wrap; gap:12px;
        margin-bottom:20px; }
      .fm-heading { display:flex; align-items:center; gap:10px; min-width:0; flex:1; }
      .fm-brand { display:grid; place-items:center; width:36px; height:36px;
        flex:none; border-radius:9px; background:var(--fm-accent-soft); color:var(--fm-accent-ink); }
      .fishfm .fm-eyebrow { color:var(--fm-faint); font-size:10px; letter-spacing:.12em; }
      .fishfm h1 { font-size:20px; font-weight:650; letter-spacing:-.3px; }
      .fm-subtitle { margin-top:2px!important; color:var(--fm-muted); font-size:12px; }
      .fm-top-actions { display:flex; gap:6px; flex-wrap:wrap; }
      .fm-button { position:relative; display:inline-flex; align-items:center;
        justify-content:center; gap:7px; min-height:34px; padding:6px 12px; border:1px solid var(--fm-line);
        border-radius:7px; background:var(--fm-surface); color:var(--fm-ink);
        font-size:12px; font-weight:500; transition:background-color var(--fm-fast) var(--fm-ease),
        border-color var(--fm-fast) var(--fm-ease),transform var(--fm-press) var(--fm-ease); }
      .fm-button:hover:not(:disabled) { background:var(--fm-hover); border-color:var(--fm-line-strong); }
      .fm-button:active:not(:disabled),.fm-float-icon:active:not(:disabled) { transform:scale(.97); }
      .fm-primary { background:var(--fm-accent); border-color:transparent; color:var(--fm-on-accent); overflow:hidden; }
      .fm-primary:hover:not(:disabled) { background:var(--fm-accent-hover); border-color:transparent; }
      .fm-primary:after { content:''; pointer-events:none; position:absolute; inset:0;
        background:linear-gradient(110deg,transparent 20%,color-mix(in srgb,var(--fm-on-accent) 20%,transparent) 50%,transparent 80%);
        transform:translateX(-120%); transition:transform var(--fm-sheen) var(--fm-ease); }
      .fm-primary:hover:after { transform:translateX(120%); }
      .fm-widget-pref[aria-pressed=true] { color:var(--fm-accent-ink); background:var(--fm-accent-soft); }
      .fm-hero { display:grid; grid-template-columns:minmax(0,1fr) 120px; align-items:center; gap:16px;
        padding:22px; margin-bottom:16px; background:var(--fm-surface); border:1px solid var(--fm-line);
        border-radius:12px; box-shadow:var(--fm-shadow); animation:fm-rise var(--fm-page) var(--fm-ease) both; }
      .fm-art { grid-column:2; grid-row:1; display:grid; place-items:center; align-self:stretch;
        background:var(--fm-accent-soft); border-radius:10px; overflow:hidden; }
      .fm-art img { width:120px; height:145px; object-fit:contain; animation:fm-swap var(--fm-base) var(--fm-ease); }
      .fm-hero-copy { grid-column:1; grid-row:1; min-width:0; }
      .fm-live,.fm-float-status { display:flex; align-items:center; gap:7px; color:var(--fm-muted); font-size:11px; }
      .fm-dot,.fm-float-dot { display:inline-block; width:6px; height:6px; flex:none;
        border-radius:50%; background:var(--fm-ok); }
      .fm-dot[data-off=true],.fm-float-dot[data-off=true] { background:var(--fm-warn); }
      .fm-track { margin:10px 0 4px!important; font-size:24px; font-weight:650;
        letter-spacing:-.5px; line-height:1.3; overflow-wrap:anywhere; }
      .fm-artist { color:var(--fm-muted); font-size:12px; }
      .fm-track-swap { animation:fm-swap var(--fm-fast) var(--fm-ease) both; }
      .fm-progress { height:4px; overflow:hidden; margin:16px 0 6px; border-radius:99px; background:var(--fm-line); }
      .fm-progress span { display:block; height:100%; border-radius:inherit; background:var(--fm-accent);
        transition:width var(--fm-fast) linear; }
      .fm-time { display:flex; justify-content:space-between; gap:8px; color:var(--fm-faint);
        font-size:10px; font-variant-numeric:tabular-nums; }
      .fm-controls { display:flex; gap:7px; flex-wrap:wrap; margin-top:14px; }
      .fm-wave { display:flex; align-items:center; gap:2px; height:12px; }
      .fm-wave i { width:2px; height:8px; background:var(--fm-ok); border-radius:2px;
        animation:fm-wave 850ms ease-in-out infinite alternate; }
      .fm-wave i:nth-child(2) { animation-delay:-300ms; height:12px; }
      .fm-wave i:nth-child(3) { animation-delay:-550ms; }
      .fm-grid { display:grid; grid-template-columns:minmax(0,1fr) 320px; align-items:start; gap:20px; }
      .fm-main-column,.fm-controls-column { min-width:0; }
      .fm-grid>*>section:first-child h2 { margin-top:0; }
      .fishfm section { min-width:0; }
      .fishfm h2 { display:flex; gap:8px; align-items:baseline; margin:17px 0 8px;
        font-size:13px; font-weight:600; }
      .fishfm h2 small { color:var(--fm-faint); font-size:9px; font-weight:500; letter-spacing:.1em; }
      .fm-card { padding:4px 14px; border:1px solid var(--fm-line); border-radius:9px; background:var(--fm-surface); }
      .fm-persona-card { padding:16px; }
      .fm-section-head { display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:8px; }
      .fm-facts { display:flex; flex-wrap:wrap; gap:6px; margin:12px 0; }
      .fm-fact { padding:5px 9px; border-radius:6px; background:var(--fm-sunken); color:var(--fm-muted); font-size:11px; overflow-wrap:anywhere; min-width:0; }
      .fm-summary { padding-top:14px; border-top:1px solid var(--fm-line); margin-top:14px; }
      .fishfm .fm-summary-text { margin:12px 0; white-space:pre-wrap; overflow-wrap:anywhere; line-height:1.85; font-size:13px; }
      .fm-summary-actions { display:flex; flex-wrap:wrap; align-items:center; gap:8px; margin-top:12px; }
      .fm-summary-actions select { flex:1 1 180px; min-width:0; width:100%; max-width:100%; min-height:34px; padding:6px 9px; color:var(--fm-ink); background:var(--fm-surface); border:1px solid var(--fm-line); border-radius:7px; }
      .fm-token-strip { display:grid; grid-template-columns:1fr 1fr; gap:8px 16px; padding:13px 14px; margin:16px 0 4px; background:var(--fm-sunken); border-radius:7px; }
      .fm-token-strip div { display:flex; flex-direction:column; gap:4px; min-width:0; }
      .fm-token-strip span,.fm-token-strip p { color:var(--fm-muted); font-size:10px; overflow-wrap:anywhere; }
      .fm-token-strip strong { font-size:20px; font-weight:600; font-variant-numeric:tabular-nums; overflow-wrap:anywhere; }
      .fm-token-strip small { font-size:10px; color:var(--fm-faint); font-weight:400; }
      .fm-token-strip p { grid-column:1/-1; }
      .fishfm details>summary { cursor:pointer; font-size:12px; line-height:1.7; overflow-wrap:anywhere; }
      .fm-disclosure { border-top:1px solid var(--fm-line); }
      .fm-disclosure:first-of-type { border-top:0; }
      .fm-disclosure>summary { padding:12px 0; }
      .fm-disclosure-meta { margin-left:8px; color:var(--fm-faint); font-size:10px; font-weight:400; }
      .fm-disclosure-body { padding-bottom:10px; }
      .fm-check-row { display:flex; align-items:center; gap:8px; font-size:12px; }
      .fm-check-row input { margin:0; accent-color:var(--fm-accent); }
      .fm-budget-row { display:flex; align-items:flex-end; flex-wrap:wrap; gap:8px; padding:8px 0; }
      .fm-budget-row label { display:flex; flex:1 1 180px; align-items:center; justify-content:space-between; gap:12px; }
      .fishfm input[type=number] { width:100px; min-width:0; min-height:34px; padding:6px 8px; color:var(--fm-ink); background:var(--fm-surface); border:1px solid var(--fm-line); border-radius:7px; }
      .fm-call-history { padding:12px 0 0; }
      .fm-call { margin-top:10px; padding:10px; background:var(--fm-sunken); border-radius:6px; overflow-wrap:anywhere; }
      .fm-call .fm-note { margin-bottom:0!important; }
      .fm-input-library { padding:12px 14px; border:1px solid var(--fm-line); border-radius:9px; background:var(--fm-surface); }
      .fm-input-library>summary { font-weight:550; }
      .fm-input-library[open]>summary { margin-bottom:14px; }
      .fm-platform-details { margin-top:8px; }
      .fm-platform-details section>h2 { display:none; }
      .fm-platform-details .fm-card { padding:0; border:0; }
      .fm-platform-details .fm-platform-actions { width:100%; min-width:0; }
      .fm-platform-actions select { max-width:100%; min-width:0; min-height:32px; padding:5px 8px; border:1px solid var(--fm-line); border-radius:6px; background:var(--fm-surface); color:var(--fm-ink); }
      .fm-profile-details>summary,.fm-interface-details>summary { padding:10px 0; font-weight:550; }
      .fm-interface-details { margin-top:16px; }
      .fm-reply { grid-column:1/-1; border-top:1px solid var(--fm-line); padding-top:14px; min-width:0; }
      .fm-reply .fm-label { color:var(--fm-accent-ink); font-size:11px; }
      .fishfm .fm-reply-text { margin:5px 0 8px; font-size:12px; line-height:1.75; overflow-wrap:anywhere; }
      .fm-reply details { color:var(--fm-muted); font-size:11px; }
      .fm-reply details p { margin-top:8px; overflow-wrap:anywhere; }
      .fm-track-feedback { grid-column:1/-1; display:flex; align-items:center; flex-wrap:wrap; gap:8px 14px; border-top:1px solid var(--fm-line); padding-top:12px; }
      .fm-track-feedback .fm-note { margin:0!important; }
      .fm-feedback-actions { display:flex; flex-wrap:wrap; gap:7px; }
      .fm-feedback-button[aria-pressed=true] { background:var(--fm-accent-soft); color:var(--fm-accent-ink); border-color:var(--fm-accent); }
      .fm-reset-confirm { padding:12px; border:1px solid var(--fm-line); border-radius:7px; background:var(--fm-sunken); }
      .fm-reset-confirm .fm-check-row { margin:10px 0; align-items:flex-start; font-size:11px; }
      .fm-reset-confirm input { flex:none; margin-top:2px; }
      .fm-row { display:flex; align-items:center; justify-content:space-between; gap:14px;
        padding:12px 0; border-bottom:1px solid var(--fm-line); }
      .fm-label { font-size:12px; font-weight:550; }
      .fm-row>div { min-width:0; }
      .fm-row p { margin-top:3px; color:var(--fm-muted); font-size:11px; overflow-wrap:anywhere; }
      .fm-profile-details .fm-row { flex-wrap:wrap; gap:6px; }
      .fm-profile-details .fm-row>span { overflow-wrap:anywhere; min-width:0; }
      .fm-toggle { width:32px; height:19px; padding:2px; border:0; border-radius:99px;
        flex:none; background:var(--fm-line-strong); transition:background var(--fm-fast) var(--fm-ease); }
      .fm-toggle[aria-checked=true] { background:var(--fm-accent); }
      .fm-toggle span { display:block; width:15px; height:15px; border-radius:50%; background:white;
        box-shadow:0 1px 3px hsl(222 44% 22% / .2); transition:transform var(--fm-base) var(--fm-spring); }
      .fm-toggle[aria-checked=true] span { transform:translateX(13px); }
      .fm-rate { padding:13px 0; }
      .fm-rate-head,.fm-save-line { display:flex; align-items:center; justify-content:space-between; gap:8px; }
      .fm-rate-head output { color:var(--fm-accent-ink); font-size:11px; font-variant-numeric:tabular-nums; }
      .fm-rate input { display:block; width:100%; height:4px; margin:14px 0; accent-color:var(--fm-accent); }
      .fm-save-line { align-items:flex-start; }
      .fm-save { color:var(--fm-muted); font-size:10px; overflow-wrap:anywhere; }
      .fm-modes { display:grid; grid-template-columns:1fr 1fr; gap:7px; }
      .fm-mode { display:flex; flex-direction:column; align-items:flex-start; gap:4px;
        min-height:65px; padding:11px; border:1px solid var(--fm-line); border-radius:9px;
        text-align:left; background:var(--fm-surface); color:var(--fm-ink);
        transition:background var(--fm-base) var(--fm-ease),border-color var(--fm-base) var(--fm-ease),transform var(--fm-press) var(--fm-ease); }
      .fm-mode strong { font-size:12px; font-weight:550; }
      .fm-mode span { color:var(--fm-muted); font-size:10px; }
      .fm-mode:hover:not(:disabled) { background:var(--fm-hover); }
      .fm-mode:active:not(:disabled) { transform:scale(.98); }
      .fm-mode[data-selected=true] { border-color:var(--fm-accent); background:var(--fm-accent-soft); }
      .fm-mode[data-selected=true] strong { color:var(--fm-accent-ink); }
      .fm-platform { display:flex; flex-wrap:wrap; align-items:center; gap:9px;
        padding:12px 0; border-bottom:1px solid var(--fm-line); }
      .fm-platform:last-child { border-bottom:0; }
      .fm-platform-mark { display:grid; place-items:center; width:26px; height:26px;
        border-radius:6px; background:var(--fm-sunken); color:var(--fm-accent-ink); font-size:12px; }
      .fm-platform-name { display:flex; align-items:center; gap:9px; flex:1; min-width:100px; font-size:12px; font-weight:500; }
      .fm-platform-actions { display:flex; flex-wrap:wrap; align-items:center; gap:6px; }
      .fm-badge { padding:2px 6px; border:1px solid var(--fm-line); border-radius:5px;
        color:var(--fm-muted); font-size:10px; white-space:nowrap; }
      .fm-badge[data-ok=true] { color:var(--fm-ok); background:color-mix(in srgb,var(--fm-ok) 8%,var(--fm-surface)); }
      .fm-platform-note,.fm-note { margin:10px 0!important; color:var(--fm-muted); font-size:11px; line-height:1.65; overflow-wrap:anywhere; }
      .fm-notice,.fm-import { padding:10px 12px; margin:10px 0; background:var(--fm-accent-soft);
        color:var(--fm-accent-ink); border:1px solid var(--fm-line); border-radius:7px; font-size:11px;
        overflow-wrap:anywhere; animation:fm-swap var(--fm-fast) var(--fm-ease); }
      .fm-notice[data-error=true] { background:color-mix(in srgb,var(--fm-danger) 8%,var(--fm-surface)); color:var(--fm-danger); }
      .fm-login { padding:14px; margin:10px 0; background:var(--fm-sunken);
        border:1px solid var(--fm-line); border-radius:8px; text-align:center; font-size:12px; }
      .fm-login img { display:block; width:170px; height:170px; max-width:100%; margin:12px auto; border-radius:5px; }
      .fm-login .fm-button { margin:8px 3px 0; }
      .fm-attempts { margin:8px 0; font-size:10px; color:var(--fm-muted); }
      .fm-attempts-title { margin:6px 0; font-weight:550; }
      .fm-attempt { display:flex; align-items:center; justify-content:space-between; padding:7px 0; border-top:1px solid var(--fm-line); }
      .fm-attempt-note { margin-left:8px; color:var(--fm-faint); }
      .fm-motion-row { display:flex; flex-wrap:wrap; align-items:center; justify-content:space-between; gap:8px; padding:12px 0; }
      .fm-motion-row select { padding:5px 8px; border:1px solid var(--fm-line); border-radius:6px;
        color:var(--fm-ink); background:var(--fm-surface); font-size:11px; }
      .fm-widget-note { display:flex; gap:8px; align-items:center; padding:12px 0; color:var(--fm-muted); font-size:11px; }
      .fm-widget-note .fm-button { margin-left:auto; }
      .fm-foot { display:flex; flex-wrap:wrap; justify-content:space-between; gap:8px;
        margin-top:22px; padding-top:12px; border-top:1px solid var(--fm-line); color:var(--fm-faint); font-size:10px; }
      .fm-library-head { display:flex; align-items:center; flex-wrap:wrap; justify-content:space-between; gap:8px; margin:18px 0 8px; }
      .fm-library-head h2 { margin:0; }
      .fm-library-search { width:min(220px,100%); min-height:32px; padding:6px 10px;
        border:1px solid var(--fm-line); border-radius:7px; background:var(--fm-surface); color:var(--fm-ink); font-size:12px; }
      .fm-library-list { border:1px solid var(--fm-line); border-radius:9px; overflow:hidden; background:var(--fm-surface); }
      .fm-song { display:flex; align-items:center; gap:10px; width:100%; padding:10px 12px;
        border:0; border-bottom:1px solid var(--fm-line); text-align:left; background:transparent; color:var(--fm-ink);
        transition:background var(--fm-fast) var(--fm-ease); }
      .fm-song:last-child { border-bottom:0; }
      .fm-song:hover:not(:disabled) { background:var(--fm-hover); }
      .fm-song[data-current=true] { background:var(--fm-accent-soft); }
      .fm-song-index { width:24px; flex:none; text-align:center; color:var(--fm-faint); font-size:10px; }
      .fm-song-copy { display:block; min-width:0; flex:1; }
      .fm-song-title,.fm-song-artist { display:block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }
      .fm-song-title { font-size:12px; font-weight:500; }
      .fm-song-artist { margin-top:2px; color:var(--fm-muted); font-size:10px; }
      .fm-song-duration { color:var(--fm-faint); font-variant-numeric:tabular-nums; font-size:10px; }
      .fm-song svg { color:var(--fm-accent-ink); }
      .fm-library-empty { padding:24px 16px; text-align:center; color:var(--fm-muted); font-size:12px; }
      .fm-library-foot { display:flex; justify-content:space-between; align-items:center; gap:10px;
        margin-top:8px; color:var(--fm-faint); font-size:10px; }
      .fm-library-pages { display:flex; align-items:center; gap:7px; }
      .fm-library-pages .fm-button { min-height:28px; padding:3px 8px; font-size:11px; }
      .fm-float { position:absolute; z-index:25; pointer-events:auto; width:310px; max-width:calc(100% - 24px); }
      .fm-float-pill { display:flex; align-items:center; gap:7px; padding:8px;
        border:1px solid var(--fm-line); border-radius:11px; background:var(--fm-raised); box-shadow:var(--fm-popup-shadow); }
      .fm-float-art { display:grid; place-items:center; width:40px; height:42px; flex:none;
        border-radius:7px; background:var(--fm-accent-soft); overflow:hidden; }
      .fm-float-art img { width:49px; height:49px; object-fit:contain; animation:fm-swap var(--fm-fast) var(--fm-ease); }
      .fm-float-trigger { display:flex; align-items:center; gap:8px; min-width:0; flex:1; padding:0;
        border:0; background:transparent; color:inherit; text-align:left; }
      .fm-float-copy { display:block; min-width:0; flex:1; }
      .fm-float-title,.fm-float-artist { display:block; overflow:hidden; white-space:nowrap; text-overflow:ellipsis; }
      .fm-float-title { font-size:11px; font-weight:550; }
      .fm-float-artist { margin-top:2px; color:var(--fm-muted); font-size:10px; }
      .fm-float-status { margin-top:4px; font-size:9px; }
      .fm-float-actions { display:flex; align-items:center; gap:2px; }
      .fm-float-icon,.fm-float-handle { display:grid; place-items:center; width:29px; height:29px;
        flex:none; padding:0; border:0; border-radius:6px; background:transparent; color:var(--fm-muted);
        transition:background var(--fm-fast) var(--fm-ease),transform var(--fm-press) var(--fm-ease); }
      .fm-float-icon:hover,.fm-float-handle:hover { background:var(--fm-hover); color:var(--fm-accent-ink); }
      .fm-float-handle { width:17px; touch-action:none; cursor:grab!important; }
      .fm-float-handle:active { cursor:grabbing!important; }
      .fm-float-handle svg { width:13px; height:13px; }
      .fm-float-drawer,.fm-float-menu { position:absolute; right:0; bottom:calc(100% + 9px);
        border:1px solid var(--fm-line); border-radius:10px; background:var(--fm-raised);
        box-shadow:var(--fm-popup-shadow); transform-origin:bottom right;
        animation:fm-pop-in var(--fm-base) var(--fm-ease) both; }
      .fm-float[data-edge=left] :is(.fm-float-drawer,.fm-float-menu) { left:0; right:auto; transform-origin:bottom left; }
      .fm-float[data-pop-side=below] :is(.fm-float-drawer,.fm-float-menu) { top:calc(100% + 9px); bottom:auto; transform-origin:top right; }
      .fm-float[data-edge=left][data-pop-side=below] :is(.fm-float-drawer,.fm-float-menu) { transform-origin:top left; }
      :is(.fm-float-drawer,.fm-float-menu)[data-phase=exit] { animation:fm-pop-out var(--fm-fast) var(--fm-ease) both; pointer-events:none; }
      .fm-float-drawer { width:min(330px,calc(100vw - 28px)); overflow:hidden; max-height:var(--fm-pop-max,70vh); }
      .fm-float-drawer-head { display:flex; align-items:center; justify-content:space-between; gap:8px; padding:0 12px 7px; }
      .fm-float-drawer-label { color:var(--fm-muted); font-size:10px; font-weight:550; }
      .fm-float-drawer-body { padding:0 12px 13px; overflow:auto; max-height:calc(var(--fm-pop-max,70vh) - 52px); }
      .fm-float-track { padding:5px 0 0; }
      .fm-float-track strong { display:block; font-size:14px; line-height:1.4; overflow-wrap:anywhere; }
      .fm-float-track span { display:block; margin-top:3px; color:var(--fm-muted); font-size:11px; }
      .fm-float-controls { display:grid; grid-template-columns:1fr 1fr; gap:7px; margin-top:13px; }
      .fm-float-empty { padding:8px 0; color:var(--fm-muted); font-size:11px; }
      .fm-float-menu { z-index:3; width:220px; padding:5px; max-height:var(--fm-pop-max,70vh); overflow:auto; }
      .fm-float-menu button { display:flex; align-items:center; justify-content:space-between; gap:10px;
        width:100%; min-height:33px; padding:6px 9px; border:0; border-radius:5px;
        background:transparent; color:var(--fm-ink); text-align:left; font-size:11px; }
      .fm-float-menu button:hover,.fm-float-menu button:focus-visible { background:var(--fm-hover); }
      .fm-menu-section { padding:6px 9px 4px; color:var(--fm-faint); font-size:9px; }
      .fm-menu-check { color:var(--fm-accent-ink); font-weight:600; }
      .fm-menu-sep { height:1px; margin:5px 4px; background:var(--fm-line); }
      .fm-float-hint { padding:6px 8px 3px; color:var(--fm-faint); font-size:9px; }
      .fm-handle { display:grid; place-items:center; width:100%; height:24px; padding:0;
        border:0; background:transparent; touch-action:none; cursor:grab!important; }
      .fm-handle-bar { width:30px; height:3px; border-radius:9px; background:var(--fm-line-strong); }
      @keyframes fm-page-in { from{opacity:0;transform:translateY(var(--fm-motion-shift));filter:blur(1px)} to{opacity:1;transform:none;filter:none} }
      @keyframes fm-rise { from{opacity:0;transform:translateY(var(--fm-motion-shift))} to{opacity:1;transform:none} }
      @keyframes fm-swap { from{opacity:0;transform:translateY(var(--fm-motion-shift))} to{opacity:1;transform:none} }
      @keyframes fm-pop-in { from{opacity:0;transform:translateY(var(--fm-motion-shift)) scale(.97)} to{opacity:1;transform:none} }
      @keyframes fm-pop-out { from{opacity:1;transform:none} to{opacity:0;transform:translateY(var(--fm-motion-shift)) scale(.98)} }
      @keyframes fm-wave { from{transform:scaleY(.35)} to{transform:scaleY(1)} }
      @keyframes fm-settle { from{transform:scale(.985)} to{transform:scale(1)} }
      .fm-float[data-dragging=false] .fm-float-pill { animation:fm-settle var(--fm-base) var(--fm-ease); }
      .fishfm[data-view=settings] .fm-grid { grid-template-columns:1fr; }
      @container fishfm (max-width:740px) { .fm-grid{grid-template-columns:1fr;gap:20px} .fm-hero{grid-template-columns:minmax(0,1fr) 96px;padding:17px;gap:12px} .fm-art img{width:96px;height:130px} .fm-track{font-size:21px} }
      @container fishfm (max-width:460px) { .fm-top-actions{width:100%} .fm-hero{grid-template-columns:minmax(0,1fr) 64px;padding:14px;gap:8px} .fm-art img{width:64px;height:100px} .fm-track{font-size:18px} .fm-controls .fm-button{padding:5px 8px;min-height:32px;font-size:11px} .fm-library-search{width:100%} .fm-persona-card{padding:14px} .fm-summary-actions .fm-button{width:100%} .fm-library-foot{flex-wrap:wrap} .fm-profile-details .fm-badge{white-space:normal} }
      @media(max-width:600px) { .fishfm{padding:16px} .fm-float{width:290px} }
      @media(prefers-reduced-motion:reduce) { :is(.fishfm,.fm-float) *, :is(.fishfm,.fm-float){animation:none!important;transition:none!important;scroll-behavior:auto!important} }
      :is(.fishfm,.fm-float)[data-motion=off] *, :is(.fishfm,.fm-float)[data-motion=off]{animation:none!important;transition:none!important}
      :is(.fishfm,.fm-float)[data-motion=reduced] .fm-wave i { animation:none; }
    `;

    // src/ui/client/shared.mjs
    const h = React.createElement;
    const minutes = ms => { const seconds = Math.floor(Math.max(0, ms || 0) / 1000); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}`; };
    const progressPercent = current => {
      const duration = current?.track?.durationMs;
      return Number.isFinite(duration) && duration > 0
        ? Math.min(100, 100 * Math.max(0, current.positionMs || 0) / duration) : 0;
    };
    const modes = [['normal', '日常', '自主选歌 · 保留声音'], ['focus', '专注', '减少中途切换'], ['silent', '静听', '自主播放 · 电脑静音'], ['off', '关闭', '暂停并停止自动听歌']];
    const sourceNames = { recent: '近期记录', liked: '喜欢列表', playlist: '用户歌单' };
    const stageNames = { login_status: '读取登录状态', user_record: '请求近期记录', likelist: '读取喜欢列表', user_playlist: '读取用户歌单', playlist_detail: '读取歌单详情', song_detail: '读取歌曲详情', accountInfo: '读取登录状态', recentTracks: '请求近期记录', likedTracks: '读取喜欢列表', playlists: '读取用户歌单', playlistTracks: '读取歌单详情', songDetails: '读取歌曲详情' };

    // src/ui/client/presentation.mjs
    function playbackPresentation(snapshot, connected) {
      if (!connected) return { label: snapshot ? '连接中断 · 保留上次状态' : '正在连接电台', art: 'whale-idle', active: false };
      if (snapshot?.status === 'resolving' || snapshot?.status === 'selecting') return { label: '正在准备音乐', art: 'whale-dj', active: false };
      if (snapshot?.lastError) return { label: '播放未成功', art: 'whale-idle', active: false };
      if (snapshot?.paused) return { label: '已暂停 · 不会自动恢复', art: 'whale-idle', active: false };
      if (snapshot?.status === 'playing') return { label: snapshot.settings?.humanPlayback ? '正在播放' : '静音播放', art: 'whale-listening', active: true };
      return { label: '电台待命', art: 'whale-idle', active: false };
    }

    function filterLibrary(tracks, query) {
      const needle = String(query ?? '').trim().toLocaleLowerCase();
      return (tracks ?? []).filter(track => !needle || `${track.title || ''} ${track.artist || ''} ${track.providerTrackId || ''}`.toLocaleLowerCase().includes(needle));
    }

    function discoveryPresentation(snapshot) {
      const data = snapshot?.discovery;
      if (!snapshot?.settings?.discovery || snapshot.settings.discoveryRate === 0) return '探索已关闭；自主选择使用熟悉歌曲。';
      if (!data) return '推荐候选状态尚未读取。';
      const names = { netease_daily: '网易云每日推荐', netease_personal_fm: '网易云私人 FM', netease_similar:'种子相似歌曲', platform_recommendation: '平台推荐' };
      const sources = (data.sources ?? []).map(source => names[source] || '平台推荐').join('、');
      if (data.refreshing) return `正在后台刷新；现有陌生候选 ${data.count ?? 0} 首。`;
      if (data.count > 0) return `陌生候选 ${data.count} 首${sources ? ` · ${sources}` : ''}${data.reason ? '；刷新暂未成功，保留有效缓存。' : ''}`;
      if (data.state === 'idle') return '等待后台获取推荐候选。';
      if (data.reason === 'login-required') return '推荐需要有效登录；暂从熟悉歌曲选择。';
      if (data.state === 'empty') return '暂时没有可用陌生候选；自主选择会回退熟悉歌曲。';
      return '推荐暂不可用；自主选择会回退熟悉歌曲。';
    }

    function popupPlacement(frame, bar, requestedHeight = 340) {
      const above = Math.max(0, bar.top - frame.top - 12);
      const below = Math.max(0, frame.bottom - bar.bottom - 12);
      const side = above >= requestedHeight || above >= below ? 'above' : 'below';
      return { side, maxHeight: Math.max(0, Math.min(requestedHeight, side === 'above' ? above : below)) };
    }

    // src/ui/client/controller.mjs
    const WIDGET_VISIBLE_KEY = 'fishfm.widget.visible.v1';
    const WIDGET_POSITION_KEY = 'fishfm.widget.position.v1';
    const MOTION_KEY = 'fishfm.motion.v1';
    const readPreference = (key, fallback) => {
      try {
        const value = window.localStorage.getItem(key);
        return value === null ? fallback : JSON.parse(value);
      } catch { return fallback; }
    };
    const writePreference = (key, value) => {
      try { window.localStorage.setItem(key, JSON.stringify(value)); } catch { /* storage can be disabled */ }
    };

    function createController(connection) {
      let state = {
        snapshot: null, platforms: {}, busy: false, connected: false, error: '', notice: '',
        login: null, imported: null, importAttempts: [], library: { total: 0, tracks: [] },
        widgetVisible: readPreference(WIDGET_VISIBLE_KEY, true) !== false,
        widgetPosition: readPreference(WIDGET_POSITION_KEY, null),
        motion: ['full', 'reduced', 'off'].includes(readPreference(MOTION_KEY, 'full')) ? readPreference(MOTION_KEY, 'full') : 'full',
      };
      let epoch = 0, timer, read, write,summaryWrite, disposed = false;
      const listeners = new Set();
      const emit = (patch) => { if (!disposed) {if(patch.persona?.generatedAt<state.persona?.generatedAt){patch={...patch};delete patch.persona;} state = { ...state, ...patch }; listeners.forEach(fn => fn()); } };
      const failure = error => `${error?.message || '音乐服务连接失败，请刷新重试。'}${error?.code ? ` (${error.code})` : ''}`;
      async function refresh() {
        if (disposed || state.busy || read) return;
        const version = ++epoch;
        const controller = new AbortController();
        read = controller;
        const timeout = setTimeout(() => controller.abort(), 18000);
        try {
          const result = await connection.rpc.call('/api', 'fishfm/state', {}, controller.signal);
          if (version !== epoch) return;
          if (!result.ok) throw result.error;
          const discovery = result.value.snapshot?.discovery;
          const finishedDiscovery = state.notice === '正在后台刷新推荐候选…' && discovery && !discovery.refreshing;
          emit({ ...result.value, connected: true, error: '', ...(finishedDiscovery ? {
            notice: discovery.state === 'disabled' ? '探索已关闭。' : discovery.reason && discovery.reason !== 'no-unfamiliar-candidates'
              ? '刷新未成功，请查看候选状态。' : '推荐候选已更新。',
          } : {}) });
        } catch (error) {
          if (version === epoch) emit({ connected: false, error: failure(error) });
        } finally {
          clearTimeout(timeout);
          if (read === controller) read = null;
        }
      }
      return {
        getSnapshot: () => state,
        setMotion(level) {
          if (!['full', 'reduced', 'off'].includes(level)) return;
          writePreference(MOTION_KEY, level);
          emit({ motion: level });
        },
        async playOrPause() {
          if (state.snapshot?.current) return this.command(state.snapshot.paused ? 'resume' : 'pause');
          // Manual mode stays manual: start one library song without enabling autonomy.
          if (!state.snapshot?.settings?.listening && state.library?.tracks?.[0]) {
            return this.command('requestTrack', state.library.tracks[0]);
          }
          return this.command('resume');
        },
        subscribe(fn) {
          listeners.add(fn);
          if (listeners.size === 1) { refresh(); timer = setInterval(() => { if (!document.hidden) refresh(); }, 2200); }
          return () => { listeners.delete(fn); if (!listeners.size) { clearInterval(timer); ++epoch; read?.abort(); read = null; } };
        },
        refresh,
        setWidgetVisible(visible) {
          const next = Boolean(visible);
          writePreference(WIDGET_VISIBLE_KEY, next);
          emit({ widgetVisible: next });
        },
        setWidgetPosition(position) {
          const next = position && ['left', 'right'].includes(position.edge) && Number.isFinite(position.top)
            ? { edge: position.edge, top: Math.round(position.top) } : null;
          writePreference(WIDGET_POSITION_KEY, next);
          emit({ widgetPosition: next });
        },
        async command(type, value) {
          if (disposed || state.busy || !state.connected) return;
          ++epoch; read?.abort(); read = null;
          emit({ busy: true, error: '', notice: ['pause', 'resume', 'next', 'requestTrack'].includes(type) ? '正在更新播放…' : '正在保存…' });
          write = new AbortController();
          const timeout = setTimeout(() => write?.abort(), 25000);
          try {
            const payload = type === 'requestTrack' ? {type,track:value} : type === 'setTrackFeedback' ? {type,...value} : {type,value};
            const result = await connection.rpc.call('/api', 'fishfm/command', payload, write.signal);
            if (!result.ok) throw result.error;
            const feedbackNotice = type==='setTrackFeedback' ? value.value===1?'已喜欢，将提高这首歌的排序权重':value.value===-1?'已降低这首歌的排序权重':'已撤销这首歌的反馈'
              :type==='resetTaste'?'已重置推荐偏好，可撤销最近一次重置':type==='undoTasteReset'?'已恢复重置前的偏好':null;
            emit({ ...result.value, notice: feedbackNotice || (['pause', 'resume', 'next', 'requestTrack'].includes(type) ? '播放控制已更新' : '已保存到本机') });
          } catch (error) {
            const actionError = ['no_candidates', 'constraint_conflict', 'invalid_command', 'media_unavailable','stale_track','summary_busy','no_reset_backup','invalid_track'].includes(error?.code);
            emit({ connected: actionError ? state.connected : false, error: failure(error), notice: actionError ? '请调整曲目或设置后重试' : '未确认操作，请刷新核对' });
          }
          finally { clearTimeout(timeout); write = null; emit({ busy: false }); }
        },
        async platformAction(action, provider, options = {}) {
          if (disposed || state.busy || !state.connected) return;
          const endpoint = ({ begin: 'fishfm/login-start', poll: 'fishfm/login-poll', import: 'fishfm/import', logout: 'fishfm/logout', discovery: 'fishfm/discovery-refresh', playlists:'fishfm/playlists' })[action];
          if (!endpoint) return;
          ++epoch; read?.abort(); read = null;
          const progress = action === 'poll' ? '正在确认手机扫码…'
            : action === 'import' ? options.source ? `正在读取${sourceNames[options.source]||'指定来源'}…` : '正在读取近期记录；若不可用会继续尝试喜欢列表和用户歌单…'
              : action === 'begin' ? '正在向网易云申请二维码…' : '正在连接音乐平台…';
          emit({ busy: true, error: '', notice: progress, importAttempts: action === 'import' ? [] : state.importAttempts });
          write = new AbortController();
          const timeout = setTimeout(() => write?.abort(), action === 'import' ? 120000 : 45000);
          try {
            const result = await connection.rpc.call('/api', endpoint, { provider,
              ...(action==='import'?{source:options.source??null,playlistId:options.playlistId??null}:{}) }, write.signal);
            if (!result.ok) throw result.error;
            const value = result.value;
            const login = Object.hasOwn(value, 'login') ? value.login : state.login;
            if (action === 'poll' && login) login.qrImage = state.login?.qrImage;
            emit({ snapshot: value.snapshot, platforms: value.platforms ?? state.platforms, library: value.library ?? state.library, login,
              insights:value.insights??state.insights,
              playlists: value.playlists??state.playlists,
              imported: action === 'logout' ? null : Object.hasOwn(value, 'imported') ? value.imported : state.imported,
              importAttempts: action === 'import' ? value.attempts ?? [] : state.importAttempts,
              connected: true, error: '',
              notice: action === 'playlists' ? `已读取 ${value.playlists?.length??0} 个歌单，请选择后导入。`
                : action === 'discovery' ? (value.discovery?.refreshing ? '正在后台刷新推荐候选…' : '候选状态已更新；刷新间隔限制仍有效。')
                : action === 'logout' ? '已退出网易云账号，本机凭据已删除。'
                : action === 'import'
                  ? `已读取${sourceNames[value.imported?.source] || '平台音乐'}：本次新增 ${value.imported?.imported ?? 0} 首，当前共 ${value.imported?.total ?? 0} 首${value.imported?.source !== 'recent' && !options.source ? '，使用备用来源' : ''}${value.imported?.total < value.imported?.requested ? '，返回数量不足目标，仍可播放' : ''}`
                  : value.login?.identityError || (value.login?.status === 'authorized' ? '登录成功，可以导入音乐。'
                    : value.login?.status === 'scanned' ? '已扫码，请在手机上确认登录。'
                      : value.login?.status === 'expired' ? '二维码已过期，请重新获取。'
                        : action === 'begin' ? '请用网易云音乐 App 扫描二维码。' : '等待手机确认…') });
          } catch (error) {
            const details = error?.details ?? {};
            let latest = {};
            try {
              const refreshed = await connection.rpc.call('/api', 'fishfm/state', {}, write.signal);
              if (refreshed?.ok) latest = refreshed.value;
            } catch { /* the periodic snapshot will retry */ }
            const accountStatus = latest.platforms?.[provider]?.account?.status;
            const login = action === 'begin' || action === 'poll'
              ? { ...(state.login ?? {}), provider, status: 'error', qrExpired: false, identityError: error.message,
                canRetryValidation: action === 'poll' && details.stage === 'login_status',
                canRetryCheck: action === 'poll' && details.stage === 'login_qr_check' }
              : accountStatus === 'login_required' ? null
              : accountStatus === 'expired' ? { provider, status: 'expired', qrExpired: false, identityError: error.message }
                : accountStatus === 'authorized' ? { ...(state.login ?? {}), provider, status: 'authorized' }
                  : { ...(state.login ?? {}), provider, status: 'error' };
            emit({ ...latest, connected: true, error: failure(error), notice: action === 'import' ? '导入没有写入空批次，可检查失败阶段后重试。' : '登录步骤未完成，可重新扫码或刷新重试。',
              importAttempts: action === 'import' ? details.attempts ?? [] : state.importAttempts,
              login });
          } finally { clearTimeout(timeout); write = null; emit({ busy: false }); }
        },
        async personaAction(action,payload){
          if(disposed||state.summaryBusy||!state.connected)return;
          summaryWrite=new AbortController();const timeout=setTimeout(()=>summaryWrite?.abort(),65000);
          const endpoint={summary:'fishfm/persona-summary',budget:'fishfm/persona-budget',output:'fishfm/persona-output',automatic:'fishfm/persona-automatic'}[action];
          const pending={summary:'正在总结聚合画像…',budget:'正在保存总结预算…',output:'正在保存单次输出上限…',automatic:'正在保存自动总结设置…'}[action];
          emit({summaryBusy:true,summaryError:'',summaryNotice:pending});
          try{
            if(!endpoint)throw Object.assign(new Error('未知的画像操作。'),{code:'invalid_command'});
            const result=await connection.rpc.call('/api',endpoint,payload,summaryWrite.signal);
            if(!result.ok)throw result.error;
            // This operation never overwrites live playback with a late snapshot.
            const notice=action==='summary'?(result.value.summaryResult?.cached?'已复用缓存，没有新增模型调用。':'总结已更新。')
              :action==='automatic'?(payload?.value?'自动总结已开启，只在画像更新且预算允许时运行。':'自动总结已关闭。')
              :action==='output'?'单次输出上限已保存。':'总结预算已保存。';
            emit({persona:result.value.persona,summaryNotice:notice});
          }catch(error){emit({summaryError:failure(error),summaryNotice:'本地选歌和旧总结仍保留。'});}
          finally{clearTimeout(timeout);summaryWrite=null;emit({summaryBusy:false});}
        },
        dispose() { disposed = true; ++epoch; clearInterval(timer); read?.abort(); write?.abort();summaryWrite?.abort(); listeners.clear(); },
      };
    }

    // src/ui/client/components.mjs
    function Svg({ type }) {
      const common = { width: 18, height: 18, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.8, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': true };
      if (type === 'headphones') return h('svg', common, h('path', { d: 'M4 13v-1a8 8 0 0 1 16 0v1' }), h('path', { d: 'M4 13h3v7H5a1 1 0 0 1-1-1v-6Zm16 0h-3v7h2a1 1 0 0 0 1-1v-6Z' }));
      if (type === 'more') return h('svg', common, h('circle', { cx: 5, cy: 12, r: 1, fill: 'currentColor' }), h('circle', { cx: 12, cy: 12, r: 1, fill: 'currentColor' }), h('circle', { cx: 19, cy: 12, r: 1, fill: 'currentColor' }));
      if (type === 'play') return h('svg', common, h('path', { d: 'm8 5 11 7-11 7V5Z', fill: 'currentColor', stroke: 'none' }));
      if (type === 'pause') return h('svg', common, h('path', { d: 'M8 5v14M16 5v14', strokeWidth: 2.7 }));
      if (type === 'next') return h('svg', common, h('path', { d: 'M6 5v14l10-7L6 5Z', fill: 'currentColor', stroke: 'none' }), h('path', { d: 'M19 5v14' }));
      if (type === 'close') return h('svg', common, h('path', { d: 'm6 6 12 12M18 6 6 18' }));
      if (type === 'grip') return h('svg', common, h('circle', { cx: 8, cy: 6, r: 1, fill: 'currentColor' }), h('circle', { cx: 16, cy: 6, r: 1, fill: 'currentColor' }), h('circle', { cx: 8, cy: 12, r: 1, fill: 'currentColor' }), h('circle', { cx: 16, cy: 12, r: 1, fill: 'currentColor' }), h('circle', { cx: 8, cy: 18, r: 1, fill: 'currentColor' }), h('circle', { cx: 16, cy: 18, r: 1, fill: 'currentColor' }));
      return h('svg', common, h('path', { d: 'M5 12h14M12 5l7 7-7 7' }));
    }

    function StatusMark({ active }) {
      return active ? h('span', { className: 'fm-wave', 'aria-hidden': true }, h('i'), h('i'), h('i'))
        : h('i', { className: 'fm-dot', 'data-off': true, 'aria-hidden': true });
    }

    function usePresence(open, level) {
      const [retained, setRetained] = React.useState(open);
      React.useEffect(() => {
        if (open) { setRetained(true); return undefined; }
        const reduced = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
        const duration = reduced || level === 'off' ? 0 : level === 'reduced' ? 88 : 160;
        // CSS starts on the next frame. Give its animationend event ownership;
        // the extra margin is a fallback for interrupted/disabled animations.
        const timer = setTimeout(() => setRetained(false), duration ? duration + 80 : 0);
        return () => clearTimeout(timer);
      }, [open, level]);
      return { mounted: open || retained, phase: open ? 'enter' : 'exit',
        onAnimationEnd: event => { if (!open && event.target === event.currentTarget) setRetained(false); } };
    }

    // Adapted from dsh-api-dashboard v1.4.5 client/client.js:92-135 under MIT.
    // Pointer-driven downward swipe closes the quick-control drawer; Escape and
    // the close button remain available to keyboard users.
    function SwipeHandle({ onClose }) {
      const st = React.useRef({ y0: 0, dy: 0, t0: 0, drawer: null, dragging: false });
      const setT = (el, dy, anim) => {
        if (!el) return;
        el.style.transition = anim ? 'transform var(--fm-base) var(--fm-ease)' : 'none';
        el.style.transform = dy > 0 ? `translateY(${dy}px)` : '';
      };
      const down = (e) => {
        const s = st.current;
        s.y0 = e.clientY; s.dy = 0; s.t0 = Date.now(); s.dragging = true;
        s.drawer = e.currentTarget.closest('.fm-float-drawer');
        if (s.drawer) s.drawer.style.transition = 'none';
        try { e.currentTarget.setPointerCapture(e.pointerId); } catch { /* PointerCapture is optional */ }
      };
      const move = (e) => {
        const s = st.current;
        if (!s.dragging) return;
        s.dy = Math.max(0, e.clientY - s.y0);
        setT(s.drawer, s.dy, false);
      };
      const end = () => {
        const s = st.current;
        if (!s.dragging) return;
        s.dragging = false;
        const elapsed = Math.max(1, Date.now() - s.t0);
        const fast = s.dy > 24 && s.dy / elapsed > .55;
        if (s.dy > 72 || fast) {
          // The shared presence transition owns exit and its reduced-motion timing.
          if (s.drawer) { s.drawer.style.transition = ''; s.drawer.style.transform = ''; }
          onClose();
        } else setT(s.drawer, 0, true);
      };
      return h('button', { type: 'button', className: 'fm-handle', 'aria-label': '向下滑动或按下收起快捷控制', title: '向下滑动收起',
        onPointerDown: down, onPointerMove: move, onPointerUp: end, onPointerCancel: end,
        onClick: (e) => { if (e.detail === 0) onClose(); } }, h('span', { className: 'fm-handle-bar' }));
    }

    // src/ui/client/library.mjs
    function Library({ state, controller }) {
      const [query, setQuery] = React.useState('');
      const [page, setPage] = React.useState(0);
      const library = state.library ?? { total: 0, tracks: [] };
      const tracks = filterLibrary(library.tracks, query);
      const pages = Math.max(1, Math.ceil(tracks.length / 12));
      const currentPage = Math.min(page, pages - 1);
      const visible = tracks.slice(currentPage * 12, (currentPage + 1) * 12);
      const current = state.snapshot?.current;
      const blocked = state.busy || !state.connected;
      return h('section', { className: 'fm-library', 'aria-label': '我的音乐库' },
        h('div', { className: 'fm-library-head' }, h('h2', null, '我的音乐', h('small', null, `${library.total} 首`)),
          h('input', { type: 'search', className: 'fm-library-search', 'aria-label': '搜索已导入曲目',
            placeholder: '搜索歌曲或艺人', value: query,
            onChange: event => { setQuery(event.target.value); setPage(0); } })),
        h('div', { className: 'fm-library-list' }, visible.length ? visible.map((track, index) => {
          const isCurrent = current?.track.provider === track.provider && current?.track.providerTrackId === track.providerTrackId;
          return h('button', { type: 'button', className: 'fm-song', key: `${track.provider}:${track.providerTrackId}`,
            'data-current': isCurrent, 'aria-label': `播放 ${track.title || track.providerTrackId} · ${track.artist || '未知艺人'}`,
            'aria-current': isCurrent ? 'true' : undefined, disabled: blocked,
            onClick: () => controller.command('requestTrack', track) },
            h('span', { className: 'fm-song-index', 'aria-hidden': true }, isCurrent ? h(Svg, { type: state.snapshot?.paused ? 'pause' : 'headphones' }) : String(currentPage * 12 + index + 1).padStart(2, '0')),
            h('span', { className: 'fm-song-copy' }, h('span', { className: 'fm-song-title' }, track.title || track.providerTrackId),
              h('span', { className: 'fm-song-artist' }, `${track.artist || '未知艺人'} · ${track.provider === 'netease' ? '网易云音乐' : 'QQ 音乐'}`)),
            h('span', { className: 'fm-song-duration' }, track.durationMs ? minutes(track.durationMs) : '--:--'), h(Svg, { type: 'play' }));
        }) : h('div', { className: 'fm-library-empty', role: 'status' }, library.total ? '没有匹配的歌曲，试试其他关键词。' : '还没有导入音乐。连接网易云后，点击“导入我的音乐”。')),
        h('div', { className: 'fm-library-foot' }, h('span', { role: 'status', 'aria-live': 'polite' }, query ? `${tracks.length} 首匹配` : `已载入 ${library.tracks.length} / ${library.total} 首 · 点击曲目即可播放`),
          pages > 1 && h('div', { className: 'fm-library-pages' },
            h('button', { type: 'button', className: 'fm-button', 'aria-label': '上一页曲目', disabled: currentPage === 0, onClick: () => setPage(currentPage - 1) }, '上一页'),
            h('span', null, `${currentPage + 1} / ${pages}`),
            h('button', { type: 'button', className: 'fm-button', 'aria-label': '下一页曲目', disabled: currentPage === pages - 1, onClick: () => setPage(currentPage + 1) }, '下一页'))));
    }

    // src/ui/client/persona.mjs
    const BLOCKED = {
      disabled: '自动总结已关闭。', busy: '已有总结正在进行。', no_facts: '还没有可总结的画像事实。',
      no_model: '先手动生成一份总结，自动更新会沿用其模型。', input_size: '聚合事实超出输入上限。',
      current: '总结已是最新，无需更新。', cooldown: '距上次总结不足 1 小时。', budget: '今日预算不足以再预留一次总结。',
      attempt_limit: '今日总结尝试次数已达上限。', interval: '距上次成功总结不足 24 小时。',
    };
    const TRIGGER = { automatic: '自动', manual: '手动' };

    function Persona({ state, controller }) {
      const view = state.persona;
      const [selected, setSelected] = React.useState(''), [budget, setBudget] = React.useState(4000), [output, setOutput] = React.useState(256);
      React.useEffect(() => {
        if (view) { setBudget(view.policy.dailyTokens); setOutput(view.policy.maxOutputTokens); }
      }, [view?.policy?.dailyTokens, view?.policy?.maxOutputTokens]);
      if (!view) return null;
      const routes = state.summaryModels ?? [], key = r => JSON.stringify([r.provider, r.model]);
      const { summary, ledger, policy, facts } = view;
      const cachedRoute = summary && routes.find(r => r.provider === summary.provider && r.model === summary.model);
      const chosen = selected || (cachedRoute ? key(cachedRoute) : routes[0] ? key(routes[0]) : '');
      const route = routes.find(r => key(r) === chosen);
      const busy = Boolean(state.summaryBusy), disabled = busy || !state.connected;
      const usageText = u => u ? `输入 ${u.inputTokens} / 输出 ${u.outputTokens}${u.cacheReadTokens ? ` / 缓存读 ${u.cacheReadTokens}` : ''}${u.cacheWriteTokens ? ` / 缓存写 ${u.cacheWriteTokens}` : ''}${Number.isFinite(u.reasoningTokens) ? ` / 推理 ${u.reasoningTokens}（输出细分）` : ''}` : '用量未知';
      const blocked = policy.automaticBlockedBy === 'not_enough_new_listens'
        ? `新增有效经历 ${policy.automaticNewListens} 次，未达 ${policy.autoMinNewListens} 次。`
        : BLOCKED[policy.automaticBlockedBy] ?? '';
      const automaticAvailable = Number.isFinite(policy.autoMinNewListens);
      const outputAvailable = Number.isFinite(policy.minOutputTokens);
      return h('section', { 'aria-label': '音乐人格与模型用量' },
        h('h2', null, '大肥鱼的音乐画像', h('small', null, 'PERSONA')),
        h('div', { className: 'fm-card fm-persona-card' },
          h('div', { className: 'fm-section-head' }, h('p', { className: 'fm-label' }, '本地事实与推荐策略'), h('span', { className: 'fm-badge' }, '规则选歌')),
          h('div', { className: 'fm-facts' },
            ...facts.artists.map(a => h('span', { className: 'fm-fact', key: a.key ?? a.name }, a.name)),
            h('span', { className: 'fm-fact' }, `有效经历 ${facts.validListens} 次`),
            h('span', { className: 'fm-fact' }, `探索目标 ${facts.discoveryEnabled ? facts.exploration : 0}%`)),
          !facts.artists.length && h('p', { className: 'fm-note' }, '尚未形成足够的艺人偏好，先导入或积累收听经历。'),
          h('p', { className: 'fm-note' }, '按本地偏好、平台候选与重复限制选歌。艺人标签展示较高权重，经历数仅覆盖已追踪窗口；流派和情绪未知。'),
          h('div', { className: 'fm-summary' },
            h('div', { className: 'fm-section-head' }, h('p', { className: 'fm-label' }, '模型总结'), h('span', { className: 'fm-badge' }, summary ? view.summaryStale ? '画像已变化' : '已缓存' : '按需生成')),
            summary ? h(React.Fragment, null,
              h('p', { className: 'fm-summary-text' }, summary.text),
              h('p', { className: 'fm-note fm-summary-meta' }, `${summary.provider} / ${summary.model} · ${new Date(summary.generatedAt).toLocaleString()} · ${TRIGGER[summary.trigger] ?? '手动'}触发`))
              : h('p', { className: 'fm-note' }, '还没有模型总结。播放和逐曲回复不会自动调用模型。'),
            h('div', { className: 'fm-summary-actions' },
              h('select', { 'aria-label': '总结模型', value: chosen, disabled: disabled || !routes.length, onChange: e => setSelected(e.target.value) },
                ...(routes.length ? routes.map(r => h('option', { key: key(r), value: key(r) }, r.label)) : [h('option', { value: '' }, 'DSH 模型列表尚不可用')])),
              h('button', { type: 'button', className: 'fm-button', disabled: disabled || !state.features?.personaSummary || !route,
                onClick: () => controller.personaAction('summary', { provider: route.provider, model: route.model }) }, busy ? '正在处理…' : '根据画像总结一次')),
            h('p', { className: 'fm-note', role: 'status', 'aria-live': 'polite' }, state.summaryError || state.summaryNotice || '只发送聚合事实；相同画像和模型复用缓存。总结仅作展示，不改变选歌权重。')),
          h('div', { className: 'fm-token-strip', 'aria-label': '插件模型用量' },
            h('div', null, h('span', null, '今日已知用量'), h('strong', null, ledger.today.knownTokens, h('small', null, ' tokens'))),
            h('div', null, h('span', null, '累计已知用量'), h('strong', null, ledger.total.knownTokens, h('small', null, ' tokens'))),
            h('p', null, `共 ${ledger.total.attempts} 次尝试 · ${ledger.total.unknownCalls} 次用量未知或进行中`)),
          h('details', { className: 'fm-disclosure' },
            h('summary', null, '自动总结', h('span', { className: 'fm-disclosure-meta' }, policy.automatic ? '已开启' : '默认关闭')),
            h('div', { className: 'fm-disclosure-body' },
              h('label', { className: 'fm-check-row' }, h('input', { type: 'checkbox', checked: policy.automatic === true, disabled: disabled || !automaticAvailable,
                'aria-label': '开启自动总结', onChange: e => controller.personaAction('automatic', { value: e.target.checked }) }), '开启低频自动总结'),
              h('p', { className: 'fm-note', role: 'status', 'aria-live': 'polite' }, policy.automatic
                ? policy.automaticDue ? '条件已满足，下一次检查会运行一次总结。' : blocked || '尚未满足自动总结条件。'
                : '关闭时不会自动产生模型请求。'),
              h('p', { className: 'fm-note' }, automaticAvailable
                ? `沿用上次成功总结的模型；新增有效经历 ${policy.autoMinNewListens} 次、距上次至少 24 小时、冷却 1 小时，每日最多 3 次尝试，且画像与预算允许。`
                : '当前 Core 尚未提供自动总结设置。'))),
          h('details', { className: 'fm-disclosure' }, h('summary', null, '插件 token 账本与预算', h('span', { className: 'fm-disclosure-meta' }, `今日剩余 ${ledger.remainingTokens}`)),
            h('div', { className: 'fm-disclosure-body' },
              h('p', { className: 'fm-note' }, `本地选歌 / 逐曲回复：${ledger.localDecisionRequests} 次模型调用。未知用量按保守预留扣预算；DSH 主任务和共享上下文成本未归因，不计入这里。`),
              summary && h('p', { className: 'fm-note' }, `当前总结：${usageText(summary.usage)}`),
              h('div', { className: 'fm-budget-row' },
                h('label', { className: 'fm-label' }, '每日总结预算', h('input', { type: 'number', 'aria-label': '每日总结 token 预算', min: 0, max: 100000, step: 100, value: budget, onChange: e => setBudget(Number(e.target.value)) })),
                h('button', { type: 'button', className: 'fm-button', disabled: disabled || !Number.isSafeInteger(budget) || budget < 0 || budget > 100000, onClick: () => controller.personaAction('budget', { value: budget }) }, '保存预算')),
              h('div', { className: 'fm-budget-row' },
                h('label', { className: 'fm-label' }, '单次输出上限', h('input', { type: 'number', 'aria-label': '单次输出 token 上限', min: policy.minOutputTokens ?? 64, max: policy.outputMaximumTokens ?? 256, step: 32, value: output, disabled: !outputAvailable, onChange: e => setOutput(Number(e.target.value)) })),
                h('button', { type: 'button', className: 'fm-button', disabled: disabled || !outputAvailable || !Number.isSafeInteger(output) || output < policy.minOutputTokens || output > (policy.outputMaximumTokens ?? 256), onClick: () => controller.personaAction('output', { value: output }) }, '保存上限')),
              !outputAvailable && h('p', { className: 'fm-note' }, '当前 Core 尚未提供输出上限设置。'),
              h('details', { className: 'fm-call-history' }, h('summary', null, '最近调用明细'),
                ...(ledger.recent ?? []).map(r => h('div', { className: 'fm-call', key: r.callId },
                  h('p', { className: 'fm-label' }, `${r.model} · ${r.status}`),
                  h('p', { className: 'fm-note' }, `${new Date(r.startedAt).toLocaleString()} · ${usageText(r.usage)}`))),
                !(ledger.recent?.length) && h('p', { className: 'fm-note' }, '暂无调用记录。')),
              h('p', { className: 'fm-note' }, `聚合事实 ${policy.factsBytes} / ${policy.maxPromptBytes} 字节（UTF-8，不是精确 token 数）。实际用量以模型返回为准。`)))));
    }

    // src/ui/client/feedback.mjs
    function FeedbackSettings({state,controller}) {
      const [confirm,setConfirm]=React.useState(false),[clearFeedback,setClearFeedback]=React.useState(false);
      const feedback=state.insights?.feedback,available=feedback?.version===1;
      const disabled=state.busy||state.summaryBusy||!state.connected||!available;
      return h('section',null,h('h2',null,'推荐反馈',h('small',null,'FEEDBACK')),
        h('div',{className:'fm-card'},
          available?h('p',{className:'fm-note'},`喜欢 ${feedback.liked} 首 · 少推荐 ${feedback.reduced} 首。手动反馈独立保存，不会被自动成长覆盖。`)
            :h('p',{className:'fm-note'},'当前 Core 尚未提供反馈功能，重新加载新版插件后可用。'),
          h('details',{className:'fm-disclosure'},h('summary',null,'偏好重置与恢复'),h('div',{className:'fm-disclosure-body'},
            h('p',{className:'fm-note'},'恢复为当前输入曲库的初始偏好。保留账号、曲库、历史和 token 账本；旧模型总结会移除。'),
            feedback?.resetAt&&h('p',{className:'fm-note'},`最近重置：${new Date(feedback.resetAt).toLocaleString()}`),
            confirm?h('div',{className:'fm-reset-confirm'},
              h('p',{className:'fm-label'},'重置积累的推荐偏好？'),
              h('label',{className:'fm-check-row'},h('input',{type:'checkbox',checked:clearFeedback,disabled,'aria-label':'同时清除喜欢和少推荐反馈',onChange:e=>setClearFeedback(e.target.checked)}),'同时清除喜欢 / 少推荐反馈'),
              h('div',{className:'fm-feedback-actions'},
                h('button',{type:'button',className:'fm-button',disabled,onClick:async()=>{await controller.command('resetTaste',{clearFeedback});setConfirm(false);}},'确认重置'),
                h('button',{type:'button',className:'fm-button',disabled:state.busy,onClick:()=>setConfirm(false)},'取消')))
              :h('div',{className:'fm-feedback-actions'},
                h('button',{type:'button',className:'fm-button',disabled,onClick:()=>{setClearFeedback(false);setConfirm(true);}},'重置推荐偏好'),
                feedback?.canUndoReset&&h('button',{type:'button',className:'fm-button',disabled,onClick:()=>controller.command('undoTasteReset')},'撤销最近一次重置')),
            h('p',{className:'fm-note'},'保留最近一次恢复点。撤销会恢复旧权重，覆盖重置后的成长；再次重置会替换恢复点。')))));
    }

    // src/ui/client/panel.mjs
    function Panel({ controller, back, close }) {
      const state = React.useSyncExternalStore(controller.subscribe, controller.getSnapshot);
      const snapshot = state.snapshot;
      const settings = snapshot?.settings || {};
      const [rate, setRate] = React.useState(20);
      const [importSource,setImportSource]=React.useState('auto');
      const [playlistId,setPlaylistId]=React.useState('');
      const rateId = React.useId();
      React.useEffect(() => { if (snapshot) setRate(Math.round(settings.discoveryRate * 100)); }, [settings.discoveryRate]);
      React.useEffect(() => {
        if (!['waiting', 'scanned'].includes(state.login?.status)) return undefined;
        const poll = setInterval(() => controller.platformAction('poll', state.login.provider), 2500);
        return () => clearInterval(poll);
      }, [state.login?.status, state.login?.provider, controller]);
      const disabled = state.busy || !state.connected || !snapshot;
      const mode = !settings.listening ? (!settings.humanPlayback ? 'off' : 'manual') : !settings.humanPlayback ? 'silent' : settings.strategy === 'focus' ? 'focus' : 'normal';
      const current = snapshot?.current;
      const playing = snapshot?.status === 'playing';
      const presentation = playbackPresentation(snapshot, state.connected);
      const insights=state.insights;
      const art = presentation.art;
      const accountHint = !state.connected ? '连接中断' : ({authorized:'网易云已登录',expired:'登录已过期',signed_out:'未登录',login_required:'等待登录'}[state.platforms?.netease?.account?.status] || '查看连接');
      function toggle(title, description, field, command) {
        return h('div', { className: 'fm-row', key: field }, h('div', null, h('div', { className: 'fm-label' }, title), h('p', null, description)),
          h('button', { type: 'button', className: 'fm-toggle', role: 'switch', 'aria-label': title, 'aria-checked': Boolean(settings[field]), disabled,
            onClick: () => controller.command(command, !settings[field]) }, h('span')));
      }
      const button = (label, type, blocked = false, extra = {}) => h('button', { type: 'button', className: 'fm-button', disabled: disabled || blocked, onClick: () => controller.command(type), ...extra }, label);
      const platformRows = [['netease', '网易云音乐', '网'], ['qq', 'QQ 音乐', 'Q']].map(([id, title, mark]) => {
        const platform = state.platforms?.[id];
        const label = !snapshot ? '读取中' : !platform?.installed ? '接口尚未接入' : ({
          authorized: '已登录', expired: '登录已过期', signed_out: '未登录',
          login_required: platform.account?.pending ? '等待扫码' : '未登录',
        }[platform.account?.status] || '未连接');
        const available = id === 'netease' && platform?.installed;
        const selectedPlaylist=playlistId||state.playlists?.[0]?.id||'';
        const action = platform?.account?.status === 'authorized'
          ? h(React.Fragment, null,
            state.features?.importSources&&h('select',{ 'aria-label':'导入来源',value:importSource,disabled:state.busy||!state.connected,
              onChange:e=>{setImportSource(e.target.value);if(e.target.value==='playlist')controller.platformAction('playlists',id);} },
              h('option',{value:'auto'},'自动来源'),h('option',{value:'recent'},'近期播放'),h('option',{value:'liked'},'我喜欢'),h('option',{value:'playlist'},'指定歌单')),
            state.features?.importSources&&importSource==='playlist'&&h('select',{'aria-label':'输入歌单',value:selectedPlaylist,disabled:state.busy||!state.playlists?.length,
              onChange:e=>setPlaylistId(e.target.value)},...(state.playlists?.length?state.playlists.map(p=>h('option',{key:p.id,value:p.id},p.title)):[h('option',{value:''},'读取歌单…')])),
            h('button', { type: 'button', className: 'fm-button fm-primary', disabled: state.busy || !state.connected || (importSource==='playlist'&&!selectedPlaylist),
              onClick: () => controller.platformAction('import', id,{source:importSource==='auto'?null:importSource,playlistId:importSource==='playlist'?selectedPlaylist:null}) }, '导入我的音乐'),
            h('button', { type: 'button', className: 'fm-button fm-subtle', disabled: state.busy || !state.connected,
              onClick: () => controller.platformAction('logout', id) }, '退出'))
          : available && !state.login && h('button', { type: 'button', className: 'fm-button fm-primary', disabled: state.busy || !state.connected,
            onClick: () => controller.platformAction('begin', id) }, '扫码登录');
        return h('div', { className: 'fm-platform', key: id },
          h('div', { className: 'fm-platform-name' }, h('span', { className: 'fm-platform-mark', 'aria-hidden': true }, mark), title),
          h('div', { className: 'fm-platform-actions' }, h('span', { className: 'fm-badge', 'data-ok': platform?.account?.status === 'authorized' || undefined }, label), action));
      });
      const loginPanel = state.login?.provider === 'netease'
        ? h('div', { className: 'fm-login' },
          h('div', { className: 'fm-label' }, state.login.status === 'authorized' ? '网易云音乐已连接'
            : state.login.status === 'scanned' ? '已扫码，请在手机上确认'
              : state.login.status === 'expired' ? state.login.qrExpired === false ? '登录已失效' : '二维码已过期'
                : state.login.status === 'error' ? state.login.canRetryValidation ? '登录校验未通过' : '登录未完成' : '使用网易云音乐 App 扫描'),
          state.login.qrImage && !['authorized', 'expired', 'error'].includes(state.login.status)
            && h('img', { src: state.login.qrImage, width: 172, height: 172, alt: '网易云音乐登录二维码' }),
          h('p', { role: 'status', 'aria-live': 'polite' }, state.login.identityError || (state.login.status === 'authorized'
            ? state.login.accountId ? `账号已连接（ID ${state.login.accountId}），可以导入音乐。` : '账号已连接；导入前会自动补读账号 ID。'
            : state.login.status === 'expired' ? '请重新获取二维码后再试。' : '手机确认后会自动读取账号状态，随后即可导入音乐。')),
          (state.login.canRetryValidation || state.login.canRetryCheck) && state.login.status === 'error'
            && h('button', { type: 'button', className: 'fm-button', disabled: state.busy || !state.connected,
              onClick: () => controller.platformAction('poll', 'netease') }, state.login.canRetryValidation ? '重试登录校验' : '重试扫码检测'),
          ['expired', 'error'].includes(state.login.status)
            && h('button', { type: 'button', className: 'fm-button fm-primary', disabled: state.busy || !state.connected,
              onClick: () => controller.platformAction('begin', 'netease') }, '重新获取二维码'))
        : null;
      const importNotice = state.imported
        ? h('div', { className: 'fm-import', role: 'status', 'aria-live': 'polite' },
          h('strong', null, `最近导入：${sourceNames[state.imported.source] || state.imported.source || '平台音乐'}`),
          ` · 新增 ${state.imported.imported ?? 0} 首，当前共 ${state.imported.total ?? 0} 首`,
          state.imported.degraded && state.imported.reason ? h('span', null, ` · ${state.imported.reason}`) : null)
        : null;
      const attempts = Array.isArray(state.importAttempts) && state.importAttempts.length
        ? h('div', { className: 'fm-attempts' }, h('div', { className: 'fm-attempts-title' }, '本次来源尝试'),
          state.importAttempts.map((row, index) => h('div', { className: 'fm-attempt', key: `${row.source}-${index}` },
            h('div', null, h('strong', null, sourceNames[row.source] || row.source),
              h('span', { className: 'fm-attempt-note' }, row.ok
                ? `可用 · ${row.count} 首`
                : `${stageNames[row.stage] || '请求'}失败${row.code ? ` · ${row.code}` : ''}${row.httpStatus ? ` · HTTP ${row.httpStatus}` : ''}${row.platformCode ? ` · 接口码 ${row.platformCode}` : ''}${row.reason ? ` · ${row.reason}` : ''}`)),
            h('span', { className: 'fm-badge', 'data-ok': row.ok || undefined }, row.ok ? `${row.count} 首` : '失败'))))
        : null;
      const platformSection = h('section', null,
        h('h2', null, '音乐平台', h('small', null, 'ACCOUNTS')),
        h('div', { className: 'fm-card' }, platformRows, loginPanel, importNotice, attempts,
          h('p', { className: 'fm-platform-note' }, '近期记录优先，读取失败时尝试喜欢列表和用户歌单。QQ 接入暂缓。登录材料仅保存在本机。')));

      const preferencesColumn = h('div', {className:'fm-main-column'},
            h(Persona,{state,controller}),
            insights&&h('section',null,h('h2',null,'偏好与经历',h('small',null,'LOCAL PROFILE')),h('details',{className:'fm-card fm-profile-details'},h('summary',null,'查看偏好权重与选歌记录'),
              h('p',{className:'fm-note'},'本地画像 · 来自已保存的独立偏好'),
              ...(insights.profile?.artists?.length?insights.profile.artists.slice(0,5).map(a=>h('div',{className:'fm-row',key:a.key},
                h('span',null,a.name),h('span',{className:'fm-badge'},`权重 ${Math.round(a.affinity*100)}% · ${['listen','listen_silent'].includes(a.source)?'有效经历':a.source==='legacy_artist_link'?'旧偏好链接':'初始化/维护'}`))):[h('p',{className:'fm-note'},'还没有足够的艺人偏好记录。')]),
              h('p',{className:'fm-note'},'流派/情绪特征尚未提供，不据歌名推断。'),
              Array.isArray(insights.profile?.tracks)&&h('details',null,h('summary',null,'查看歌曲偏好与最近变化'),
                ...(insights.profile?.tracks??[]).map(t=>h('p',{className:'fm-note',key:t.key},`${t.title} · 权重 ${Math.round(t.affinity*100)}% · ${['listen','listen_silent'].includes(t.source)?'有效经历':'初始化/维护'}`)),
                h('p',{className:'fm-label'},'最近有效更新'),
                ...(insights.recentChanges?.length?insights.recentChanges.slice(0,3).map(c=>h('p',{className:'fm-note',key:c.playInstanceId},`${c.title} · ${c.before.toFixed(3)} → ${c.after.toFixed(3)} · ${c.audible?'有声':'静音'}经历`)):[h('p',{className:'fm-note'},'此决策窗口还没有有效偏好更新。')])),
              h('details',null,h('summary',null,'查看选歌统计'),h('p',{className:'fm-note'},`最近保留 ${insights.statistics?.retainedDecisions??0} 次自主决策；探索尝试 ${insights.statistics?.explorationAttempts??0} 次，选中陌生候选 ${insights.statistics?.unfamiliarSelections??0} 次，已观测开始 ${insights.statistics?.observedStarts??0} 次，有效陌生经历 ${insights.statistics?.validUnfamiliarListens??0} 次。`),
                Number.isFinite(insights.statistics?.repeatedSelections)&&h('p',{className:'fm-note'},`其中 ${insights.statistics.repeatedSelections} 次选中歌曲在近期已有播放历史。`),
                ...(insights.decisions??[]).slice(0,3).map(d=>h('p',{className:'fm-note',key:d.decisionId},`${d.trackTitle??d.trackKey??'未选中歌曲'} · ${d.pool==='discovery'?'陌生池':d.fellBack?'熟悉池回退':'熟悉池'}${d.trackKey?'':' · 本次未开始播放'}`)),
                h('p',{className:'fm-note'},`${Number.isFinite(insights.statistics?.windowStart)?`窗口始于 ${new Date(insights.statistics.windowStart).toLocaleString()}。`:''}按已追踪的决策实例统计，历史覆盖不足时不视作全期比例。`)))));
      const controlsColumn = h('aside', {className:'fm-controls-column','aria-label':'电台设置'},
            h('section', null, h('h2', null, '听歌方式', h('small', null, 'MODES')), h('div', { className: 'fm-modes' }, modes.map(([id, title, desc]) =>
              h('button', { type: 'button', key: id, className: 'fm-mode', 'data-selected': mode === id, 'aria-pressed': mode === id, disabled,
                onClick: () => controller.command('setMode', id) }, h('strong', null, title), h('span', null, desc)))),
              mode === 'manual' && h('p', { className: 'fm-note' }, '仅手动点播：保留声音，不自动选歌。')),
            h('section', null, h('h2', null, '听歌偏好', h('small', null, 'PREFERENCES')), h('div', { className: 'fm-card' },
              toggle('DeepSeek 自主听歌', '允许自动选歌、续播，并从实际收听中成长。', 'listening', 'setListening'),
              toggle('电脑输出声音', '关闭后仍记录播放进度，但不会让电脑发声。', 'humanPlayback', 'setHumanPlayback'),
              toggle('探索新音乐', '有可用候选时尝试发现陌生歌曲。', 'discovery', 'setDiscovery'),
              h('p', { className: 'fm-note', role: 'status', 'aria-live': 'polite' }, discoveryPresentation(snapshot)),
              snapshot?.lastSelection?.fellBack && h('p', { className: 'fm-note' }, '最近一次自主选择：发现池无可用候选，已回退熟悉歌曲。'),
              state.features?.discoveryRefresh && h('button', { type: 'button', className: 'fm-button', disabled: disabled || !settings.discovery || settings.discoveryRate === 0 || state.platforms?.netease?.account?.status !== 'authorized',
                onClick: () => controller.platformAction('discovery', 'netease') }, '刷新推荐候选'),
              h('div', { className: 'fm-rate' }, h('div', { className: 'fm-rate-head' }, h('label', { htmlFor: rateId }, '新歌探索率'), h('output', { htmlFor: rateId }, `${rate}%`)),
                h('input', { id: rateId, 'aria-label': '新歌探索率', type: 'range', min: 0, max: 100, step: 1, value: rate, disabled: disabled || !settings.discovery,
                  onChange: e => setRate(Number(e.target.value)) }),
                h('div', { className: 'fm-save-line' }, h('span', { className: 'fm-save', role: 'status', 'aria-live': 'polite' }, state.notice || '开关即时保存；探索率需点击保存。'),
                  h('button', { type: 'button', className: 'fm-button', disabled: disabled || !settings.discovery || rate === Math.round(settings.discoveryRate * 100),
                    onClick: () => controller.command('setDiscoveryRate', rate / 100) }, '保存'))))),
            h('section', null, h('h2', null, '输入与连接',h('small',null,'LIBRARY')),
              h('details',{className:'fm-input-library'},h('summary',null,close?'输入音乐 · 查看和点播':`输入曲库 · ${state.library?.total??0} 首（展开查看）`),h(Library,{state,controller})),
              h('details',{className:'fm-platform-details fm-input-library'},h('summary',null,'音乐平台',h('span',{className:'fm-disclosure-meta'},accountHint)),platformSection)),
            h(FeedbackSettings,{state,controller}),
            h('section', null, h('details', { className: 'fm-card fm-interface-details' }, h('summary',null,'界面与悬浮条'),
              h('div', { className: 'fm-motion-row' }, h('label', { htmlFor: `${rateId}-motion` }, '动态效果'),
                h('select', { id: `${rateId}-motion`, 'aria-label': '动态效果', value: state.motion || 'full', onChange: event => controller.setMotion(event.target.value) },
                  h('option', { value: 'full' }, '完整'), h('option', { value: 'reduced' }, '轻量'), h('option', { value: 'off' }, '关闭'))),
              h('p', { className: 'fm-note' }, '同时遵循系统的减少动态效果设置。'),
              h('div', { className: 'fm-widget-note' }, h(Svg, { type: 'grip' }),
                h('span', null, state.widgetVisible ? '离开面板后显示，可拖动吸附。' : '悬浮条已隐藏，可随时显示。')))));
      const grid = h('div', { className: 'fm-grid' }, ...(close?[controlsColumn,preferencesColumn]:[preferencesColumn,controlsColumn]));

      return h('div', { className: 'fishfm', 'data-view':close?'settings':'main', 'data-motion': state.motion || 'full' }, h('div', { className: 'fm-wrap' },
        h('header', { className: 'fm-top' },
          h('div', { className: 'fm-heading' }, h('span', { className: 'fm-brand', 'aria-hidden': true }, h(Svg, { type: 'headphones' })),
            h('div', null, h('h1', null, '肥鱼电台'), h('p', { className: 'fm-subtitle' }, '你的音乐环境，DeepSeek 的听歌偏好。'))),
          h('div', { className: 'fm-top-actions' }, h('button', { type: 'button', className: 'fm-button fm-widget-pref',
            'aria-pressed': state.widgetVisible, 'aria-label': '显示或隐藏悬浮条', onClick: () => controller.setWidgetVisible(!state.widgetVisible) }, state.widgetVisible ? '悬浮条已显示' : '显示悬浮条'),
          h('button', { type: 'button', className: 'fm-button', onClick: close || back }, close ? '关闭设置' : '返回对话'))),
        h('section', { className: 'fm-hero', 'aria-label': '当前播放' },
          h('div', { className: 'fm-art' }, h('img', { key: art, src: `/fishfm/assets/${art}.png`, alt: '鲸鱼娘音乐状态' })),
          h('div', { className: 'fm-hero-copy' },
            h('div', { className: 'fm-live', role: 'status' }, h(StatusMark, { active: presentation.active }), presentation.label),
            h('div', { className: 'fm-track-swap', key: current?.playInstanceId || 'empty' },
              h('div', { className: 'fm-track' }, current?.track?.title || '今天，从哪一首开始？'),
              h('p', { className: 'fm-artist' }, current?.track?.artist || (state.library?.total ? '从音乐库点播，或让电台为你选一首。' : '连接网易云，导入常听的音乐。'))),
            current&&h('p',{className:'fm-note'},current.selectedBy==='user'?'你点播的歌曲':'大肥鱼自主选择'),
            current && h(React.Fragment, null,
              h('div', { className: 'fm-progress', 'aria-label': '播放进度' }, h('span', { style: { width: `${progressPercent(current)}%` } })),
              h('div', { className: 'fm-time' }, h('span', null, minutes(current.positionMs)), h('span', null, current.track.durationMs ? minutes(current.track.durationMs) : '--:--'))),
            h('div', { className: 'fm-controls' }, button(!current ? '开始听歌' : snapshot?.paused ? '继续播放' : '暂停', 'resume', !current && !state.library?.total && !snapshot?.queue?.length,
              { className: 'fm-button fm-primary', onClick: () => controller.playOrPause() }),
              button('下一首', 'next', !current && !snapshot?.queue?.length && !state.library?.total), button('今天停止', 'stopForToday'))),
            current&&h('div',{className:'fm-track-feedback','aria-label':'当前歌曲推荐反馈'},
              h('div',{className:'fm-feedback-actions'},
                ...[[1,'喜欢','♥'],[-1,'少推荐','↓']].map(([score,label,mark])=>h('button',{type:'button',key:score,className:'fm-button fm-feedback-button','aria-pressed':insights?.feedback?.current===score,
                  disabled:disabled||insights?.feedback?.version!==1,onClick:()=>controller.command('setTrackFeedback',{track:current.track,playInstanceId:current.playInstanceId,value:insights.feedback.current===score?0:score})},h('span',{'aria-hidden':true},mark),label))),
              h('p',{className:'fm-note',role:'status','aria-live':'polite'},insights?.feedback?.version!==1?'反馈功能需重新加载新版 Core。'
                :insights.feedback.current===1?'已喜欢：提高这首歌的排序权重。再次点击可撤销。'
                :insights.feedback.current===-1?'已少推荐：降低权重，不再作为相似推荐种子。再次点击可撤销。'
                :'仅影响肥鱼电台推荐；重复点击可撤销。')),
            insights?.explanation&&h('div',{className:'fm-reply',role:'status',key:insights.reply?.decisionId},h('p',{className:'fm-label'},'大肥鱼说'),h('p',{className:'fm-reply-text'},insights.reply?.text||insights.explanation.text),
              h('details',null,h('summary',null,'展开选歌依据'),h('p',null,`来源：${({netease_similar:'种子相似关系',netease_daily:'网易云每日推荐',netease_personal_fm:'网易云私人 FM'})[current?.origin?.source]??(current?.selectedBy==='user'?'用户指定':'熟悉歌曲')}`),
                current?.selectedBy==='agent'&&snapshot?.lastSelection?.detail&&h('p',null,`本地评分 ${snapshot.lastSelection.score?.toFixed(3)}；关系项 ${(snapshot.lastSelection.detail.relationship??0).toFixed(3)}；重复次数 ${snapshot.lastSelection.detail.repeatPlays??0}；艺人集中惩罚 ${(snapshot.lastSelection.detail.diversityPenalty??0).toFixed(3)}。`),
                Number.isFinite(snapshot?.lastSelection?.detail?.feedback)&&h('p',null,`本次决策的手动反馈评分项：${snapshot.lastSelection.detail.feedback>0?'+':''}${snapshot.lastSelection.detail.feedback.toFixed(2)}。之后的反馈从下一次决策生效。`),
                h('p',null,'解释由实际决策记录生成，逐曲不新增模型请求。')))),
        state.error && h('div', { className: 'fm-notice', 'data-error': true, role: 'alert' }, state.error,
          ' ', h('button', { className: 'fm-button', type: 'button', disabled: state.busy, onClick: controller.refresh }, '重新连接')),
        snapshot?.lastError && h('div', { className: 'fm-notice', role: 'status' }, `播放尚未成功：${snapshot.lastError.code || 'playback_failed'}。请核对平台连接和曲目权限。`),
        snapshot?.blockUntil > Date.now() && h('div', { className: 'fm-notice' }, '今天已停止自主听歌。到期后仍会保持暂停，直到你主动恢复。'),
        grid,
        h('footer', { className: 'fm-foot' }, h('span', null, '设置和登录材料保存在本机 · 关闭面板不会结束音乐服务'), h('span', null, '逐曲回复由本地规则生成 · 模型总结按需调用'))));
    }

    // src/ui/client/floating.mjs
    function FloatingPlayer({ controller, layout, usePanelInfo }) {
      const state = React.useSyncExternalStore(controller.subscribe, controller.getSnapshot);
      const activePanelId = typeof usePanelInfo === 'function' ? usePanelInfo(info => info.activePanelId) : null;
      const [expanded, setExpanded] = React.useState(false);
      const [menuOpen, setMenuOpen] = React.useState(false);
      const [dragPosition, setDragPosition] = React.useState(null);
      const [popup, setPopup] = React.useState({ side: 'above', maxHeight: 340 });
      const drawerPresence = usePresence(expanded, state.motion);
      const menuPresence = usePresence(menuOpen, state.motion);
      const rootRef = React.useRef(null);
      const triggerRef = React.useRef(null);
      const priorFocus = React.useRef(null);
      const drag = React.useRef(null);
      // Slot entries may add a zero-size wrapper. Position against the shell's
      // actual overlay frame, which owns absolute positioning and edge docking.
      const frameRect = () => {
        const root = rootRef.current;
        return (root?.closest?.('[data-shell-overlay]') ?? root?.parentElement)?.getBoundingClientRect();
      };
      const snapshot = state.snapshot;
      const current = snapshot?.current;
      const playing = snapshot?.status === 'playing';
      const paused = snapshot?.paused === true;
      const settings = snapshot?.settings || {};
      const mode = !settings.listening ? (settings.humanPlayback ? 'manual' : 'off') : !settings.humanPlayback ? 'silent' : settings.strategy === 'focus' ? 'focus' : 'normal';
      const presentation = playbackPresentation(snapshot, state.connected);
      const image = presentation.art;
      const blocked = !state.connected || state.busy;
      function openDrawer() { priorFocus.current = document.activeElement; setMenuOpen(false); setExpanded(true); }
      function openMenu() { priorFocus.current = document.activeElement; setExpanded(false); setMenuOpen(true); }
      function closeOverlay() { setExpanded(false); setMenuOpen(false); }
      React.useEffect(() => {
        if (!expanded && !menuOpen) { priorFocus.current?.focus?.(); return undefined; }
        const onKeyDown = event => {
          if (event.key === 'Escape') { event.preventDefault(); closeOverlay(); }
          if (menuOpen && ['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key)) {
            const items = Array.from(rootRef.current?.querySelectorAll('.fm-float-menu button:not(:disabled)') ?? []);
            if (!items.length) return;
            event.preventDefault();
            const currentIndex = items.indexOf(document.activeElement);
            const index = event.key === 'Home' ? 0 : event.key === 'End' ? items.length - 1
              : event.key === 'ArrowDown' ? (currentIndex + 1) % items.length : (currentIndex - 1 + items.length) % items.length;
            items[index]?.focus();
          }
        };
        const onOutside = event => { if (!rootRef.current?.contains(event.target)) closeOverlay(); };
        document.addEventListener('keydown', onKeyDown);
        document.addEventListener('pointerdown', onOutside, true);
        const focusTarget = rootRef.current?.querySelector(expanded ? '.fm-drawer-close' : '.fm-float-menu button');
        focusTarget?.focus?.();
        return () => { document.removeEventListener('keydown', onKeyDown); document.removeEventListener('pointerdown', onOutside, true); };
      }, [expanded, menuOpen]);
      React.useEffect(() => {
        if (!expanded && !menuOpen) return undefined;
        const reposition = () => {
          const frame = frameRect(), rect = rootRef.current?.getBoundingClientRect();
          if (frame && rect) setPopup(popupPlacement(frame, rect, menuOpen ? 440 : 320));
        };
        reposition();
        window.addEventListener('resize', reposition);
        return () => window.removeEventListener('resize', reposition);
      }, [expanded, menuOpen, state.widgetPosition]);
      React.useEffect(() => {
        const keepInFrame = () => {
          const root = rootRef.current;
          const position = controller.getSnapshot().widgetPosition;
          const frame = frameRect();
          const rect = root?.getBoundingClientRect();
          if (!position || !frame || !rect || frame.height <= 0) return;
          const top = Math.max(4, Math.min(position.top, frame.height - rect.height - 4));
          if (top !== position.top) controller.setWidgetPosition({ edge: position.edge, top });
        };
        window.addEventListener('resize', keepInFrame);
        return () => window.removeEventListener('resize', keepInFrame);
      }, [controller, state.widgetPosition]);
      function dragStart(event) {
        if (event.button !== undefined && event.button !== 0) return;
        const root = rootRef.current;
        const rect = root?.getBoundingClientRect();
        const frame = frameRect();
        if (!rect || !frame) return;
        drag.current = { startX: event.clientX, startY: event.clientY, left: rect.left - frame.left, top: rect.top - frame.top,
          width: rect.width, height: rect.height, frameWidth: frame.width, frameHeight: frame.height };
        closeOverlay();
        try { event.currentTarget.setPointerCapture(event.pointerId); } catch { /* PointerCapture is optional */ }
        event.preventDefault();
      }
      function dragMove(event) {
        if (!drag.current) return;
        const next = drag.current;
        next.left = Math.max(4, Math.min(next.frameWidth - next.width - 4, next.left + event.clientX - next.startX));
        next.top = Math.max(4, Math.min(next.frameHeight - next.height - 4, next.top + event.clientY - next.startY));
        next.startX = event.clientX; next.startY = event.clientY;
        setDragPosition({ left: next.left, top: next.top });
      }
      function dragEnd() {
        if (!drag.current) return;
        const next = drag.current;
        const edge = next.left + next.width / 2 < next.frameWidth / 2 ? 'left' : 'right';
        controller.setWidgetPosition({ edge, top: Math.max(4, Math.min(next.top, next.frameHeight - next.height - 4)) });
        drag.current = null;
        setDragPosition(null);
      }
      function nudge(event) {
        if (!['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End'].includes(event.key)) return;
        event.preventDefault();
        const frame = frameRect();
        const rect = rootRef.current?.getBoundingClientRect();
        if (!frame || !rect) return;
        let edge = state.widgetPosition?.edge ?? 'right';
        let top = state.widgetPosition?.top ?? frame.height - rect.height - 18;
        if (event.key === 'ArrowLeft') edge = 'left';
        if (event.key === 'ArrowRight') edge = 'right';
        if (event.key === 'ArrowUp') top -= 16;
        if (event.key === 'ArrowDown') top += 16;
        if (event.key === 'Home') top = 4;
        if (event.key === 'End') top = frame.height - rect.height - 4;
        controller.setWidgetPosition({ edge, top: Math.max(4, Math.min(frame.height - rect.height - 4, top)) });
      }
      if (!state.widgetVisible || activePanelId === 'fishfm') return null;
      const position = state.widgetPosition;
      const style = dragPosition
        ? { left: `${dragPosition.left}px`, top: `${dragPosition.top}px`, right: 'auto', bottom: 'auto' }
        : position?.edge === 'left'
          ? { left: '16px', right: 'auto', top: `${position.top}px`, bottom: 'auto' }
          : position?.edge === 'right'
            ? { right: '16px', left: 'auto', top: `${position.top}px`, bottom: 'auto' }
            : { right: '16px', bottom: '16px', left: 'auto', top: 'auto' };
      return h('div', { ref: rootRef, className: 'fm-float', style: { ...style, '--fm-pop-max': `${popup.maxHeight}px` },
        'data-motion': state.motion || 'full', 'data-dragging': Boolean(dragPosition), 'data-pop-side': popup.side,
        'data-edge': dragPosition ? 'right' : position?.edge || 'right' },
        drawerPresence.mounted && h('div', { id: 'fishfm-quick-controls', className: 'fm-float-drawer', role: 'dialog',
          'data-phase': drawerPresence.phase, onAnimationEnd: drawerPresence.onAnimationEnd,
          'aria-hidden': expanded ? undefined : true, ref: element => { if (element) element.inert = !expanded; },
          'aria-label': '音乐快捷控制', 'aria-modal': false },
          h(SwipeHandle, { onClose: () => setExpanded(false) }),
          h('div', { className: 'fm-float-drawer-head' }, h('span', { className: 'fm-float-drawer-label' }, 'FISHFM / 快捷控制'),
            h('button', { type: 'button', className: 'fm-float-icon fm-drawer-close', 'aria-label': '收起快捷控制', onClick: closeOverlay }, h(Svg, { type: 'close' }))),
          h('div', { className: 'fm-float-drawer-body' },
            current ? h(React.Fragment, null,
              h('div', { className: 'fm-float-track' }, h('strong', null, current.track?.title || '正在播放'), h('span', null, current.track?.artist || '未知艺人')),
              h('div', { className: 'fm-progress' }, h('span', { style: { width: `${progressPercent(current)}%` } })),
              h('div', { className: 'fm-time' }, h('span', null, playing ? '正在播放' : paused ? '已暂停' : '等待音乐'),
                h('span', null, `${minutes(current.positionMs)} / ${current.track?.durationMs ? minutes(current.track.durationMs) : '--:--'}`)))
              : h('div', { className: 'fm-float-empty' }, snapshot ? '当前没有播放曲目。可以打开电台设置或导入音乐。' : state.connected ? '正在读取播放状态…' : '本地音乐服务暂时无法连接。'),
            h('div', { className: 'fm-float-controls' },
              h('button', { type: 'button', className: 'fm-button fm-primary', disabled: blocked || (!current && !state.library?.total && !snapshot?.queue?.length),
                'aria-label': !current ? '开始听歌' : paused ? '继续播放' : '暂停', onClick: () => controller.playOrPause() }, h(Svg, { type: !current || paused ? 'play' : 'pause' }), !current ? '开始听歌' : paused ? '继续播放' : '暂停'),
              h('button', { type: 'button', className: 'fm-button', disabled: blocked || (!current && !snapshot?.queue?.length && !state.library?.total),
                'aria-label': '播放下一首', onClick: () => controller.command('next') }, h(Svg, { type: 'next' }), '下一首')))),
        menuPresence.mounted && h('div', { className: 'fm-float-menu', role: 'menu', 'aria-label': '音乐快捷菜单',
          'data-phase': menuPresence.phase, onAnimationEnd: menuPresence.onAnimationEnd,
          'aria-hidden': menuOpen ? undefined : true, ref: element => { if (element) element.inert = !menuOpen; } },
          h('div', { className: 'fm-menu-section' }, '快捷模式'),
          modes.map(([id, title]) => h('button', { type: 'button', key: id, role: 'menuitemradio', 'aria-checked': mode === id, disabled: blocked,
            onClick: () => { closeOverlay(); controller.command('setMode', id); } }, h('span', null, title), mode === id && h('span', { className: 'fm-menu-check', 'aria-hidden': true }, '✓'))),
          h('div', { className: 'fm-menu-sep' }),
          h('button', { type: 'button', role: 'menuitemcheckbox', 'aria-checked': Boolean(settings.listening), disabled: blocked,
            onClick: () => controller.command('setListening', !settings.listening) }, h('span', null, 'DeepSeek 自主听歌'), h('span', { className: 'fm-menu-check' }, settings.listening ? '✓' : '')),
          h('button', { type: 'button', role: 'menuitemcheckbox', 'aria-checked': Boolean(settings.humanPlayback), disabled: blocked,
            onClick: () => controller.command('setHumanPlayback', !settings.humanPlayback) }, h('span', null, '电脑输出声音'), h('span', { className: 'fm-menu-check' }, settings.humanPlayback ? '✓' : '')),
          h('button', { type: 'button', role: 'menuitemcheckbox', 'aria-checked': Boolean(settings.discovery), disabled: blocked,
            onClick: () => controller.command('setDiscovery', !settings.discovery) }, h('span', null, '探索新音乐'), h('span', { className: 'fm-menu-check' }, settings.discovery ? '✓' : '')),
          h('div', { className: 'fm-menu-sep' }),
          h('button', { type: 'button', role: 'menuitem', onClick: () => { closeOverlay(); layout.selectPanel('fishfm'); } }, h('span', null, '打开肥鱼电台设置'), h(Svg, { type: 'arrow' })),
          h('button', { type: 'button', role: 'menuitem', onClick: () => { controller.setWidgetVisible(false); closeOverlay(); } }, h('span', null, '隐藏悬浮条'), h('span', null, '×')),
          h('div', { className: 'fm-float-hint' }, `当前模式：${modes.find(([id]) => id === mode)?.[1] || '手动点播'}`)),
        h('div', { className: 'fm-float-pill' },
          h('button', { type: 'button', className: 'fm-float-handle', 'aria-label': '拖动悬浮条；使用方向键移动并吸附边缘', title: '方向键移动；Home 顶部，End 底部',
            onPointerDown: dragStart, onPointerMove: dragMove, onPointerUp: dragEnd, onPointerCancel: dragEnd, onKeyDown: nudge }, h(Svg, { type: 'grip' })),
          h('button', { ref: triggerRef, type: 'button', className: 'fm-float-trigger', 'aria-expanded': expanded, 'aria-controls': 'fishfm-quick-controls',
            onClick: () => expanded ? closeOverlay() : openDrawer() },
            h('span', { className: 'fm-float-art', 'aria-hidden': true }, h('img', { key: image, src: `/fishfm/assets/${image}.png`, alt: '' })),
            h('span', { className: 'fm-float-copy' }, h('span', { className: 'fm-float-title' }, current?.track?.title || '肥鱼电台 · 待命'),
              h('span', { className: 'fm-float-artist' }, current?.track?.artist || (state.connected ? '点击展开快捷控制' : '连接本地音乐服务中')),
              h('span', { className: 'fm-float-status' }, h(StatusMark, { active: presentation.active }), presentation.label))),
          h('div', { className: 'fm-float-actions' }, h('button', { type: 'button', className: 'fm-float-icon fm-float-more', 'aria-label': '更多音乐设置',
            'aria-haspopup': 'menu', 'aria-expanded': menuOpen, onClick: () => menuOpen ? closeOverlay() : openMenu() }, h(Svg, { type: 'more' })))),
      );
    }

    // src/ui/client/entry.mjs
    function Icon() {
      return h('svg', { width: 20, height: 20, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 1.7, 'aria-hidden': true },
        h('path', { d: 'M9 18V5l12-2v13M9 18c0 1.1-1.3 2-3 2s-3-.9-3-2 1.3-2 3-2 3 .9 3 2Zm12-2c0 1.1-1.3 2-3 2s-3-.9-3-2 1.3-2 3-2 3 .9 3 2Z' }));
    }

    function apply(ctx) {
      const controller = createController(ctx.connection);
      ctx.effect(() => {
        const style = document.createElement('style'); style.dataset.plugin = 'fishfm'; style.textContent = css; document.head.appendChild(style);
        return () => { controller.dispose(); style.remove(); };
      });
      // DSH 0.2.0-rc.1 maps null to the Conversation; 'conversation' is not a
      // registered third-party main panel key.
      const inject = () => ({ controller, back: () => ctx.layout.selectPanel(null) });
      ctx.slots.inject('main', () => ctx.slots.register({ name: 'main', key: 'fishfm', inject }, Panel));
      ctx.slots.inject('sidebar.panellist', () => ctx.slots.register({ name: 'sidebar.panellist', id: 'fishfm', order: 25, label: () => '肥鱼电台' }, Icon));
      ctx.slots.inject('settings.section', () => ctx.slots.register({ name: 'settings.section', id: 'fishfm', order: 65, label: () => '肥鱼电台', inject }, Panel));
      ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'fishfm.player', order: 30,
        inject: () => ({ controller, layout: ctx.layout }) }, FloatingPlayer));
    }
    return { apply, inject: ['slots', 'connection', 'layout'] };
  },
});
