#!/usr/bin/env node
// Interactive sign-in for a music platform, for use before or outside the DSH
// plugin. This is the entry point P3 needs: it produces a QR code to scan, waits
// for confirmation, and stores the session through the credential store. The
// secret is never printed.
//
//   node scripts/login.mjs [--provider netease|qq] [--out <dir>] [--timeout 300]
//                          [--dry-run] [--probe]
//
// `--dry-run` uses an in-memory credential store, so a test scan leaves nothing
// behind. `--probe` additionally asks the platform who we are, which is the
// first real check that the endpoint profile is right.
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve } from 'node:path';
import { neteaseEndpoints, NETEASE_ENDPOINT_PROVENANCE } from '../src/providers/endpoints/netease.mjs';
import { createHttpTransport } from '../src/providers/transport.mjs';
import { createNetEaseProvider } from '../src/providers/netease.mjs';
import { createDpapiCredentials, createMemoryCredentials } from '../src/providers/credentials-dpapi.mjs';

const argValue = (name, fallback) => {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : fallback;
};
const hasFlag = (name) => process.argv.includes(name);

const providerName = argValue('--provider', 'netease');
const timeoutSeconds = Number(argValue('--timeout', '300'));
const dryRun = hasFlag('--dry-run');
const probe = hasFlag('--probe');

if (providerName !== 'netease') {
  console.error(`Only netease is wired for sign-in so far; ${providerName} has no confirmed endpoint profile.`);
  process.exit(2);
}

// Credentials live beside the Harness home, never in the repository.
const stateDirectory = resolve(argValue('--out', join(process.env.DSH_HOME ?? join(homedir(), '.fishfm'), 'fishfm')));
const credentials = dryRun ? createMemoryCredentials() : createDpapiCredentials({ directory: join(stateDirectory, 'credentials') });
const reference = `fishfm/${providerName}`;

// A tiny store stand-in: the providers only use it for the credential reference
// row, and this command is not the long-lived host.
const referenceRows = new Map();
const store = {
  getCredentialReference: (name) => referenceRows.get(name) ?? null,
  setCredentialReference: (row) => { referenceRows.set(row.provider, { ...row, credential_ref: row.credentialRef, account_id: row.accountId, state: row.state }); },
  removeCredentialReference: (name) => { referenceRows.delete(name); },
};

const transport = createHttpTransport({
  endpoints: neteaseEndpoints(),
  onLog: (entry) => { if (entry.type === 'transport') console.log(`  · transport: ${entry.role} set ${entry.cookies} cookie(s)`); },
});
const provider = createNetEaseProvider({ transport, credentials, store, accountRef: reference });

/** Records the shape of a response without recording its contents. */
function describeShape(value, depth = 0) {
  if (value === null) return 'null';
  if (Array.isArray(value)) return `array(${value.length})${value.length && depth < 2 ? ` of ${describeShape(value[0], depth + 1)}` : ''}`;
  if (typeof value === 'object') {
    const keys = Object.keys(value).slice(0, 12);
    return `{${keys.join(', ')}${Object.keys(value).length > 12 ? ', …' : ''}}`;
  }
  // Scalars are reported by type only: a login response can contain tokens.
  return typeof value;
}

function fail(message, hint) {
  console.error(`\n✗ ${message}`);
  if (hint) console.error(`  ${hint}`);
  process.exit(1);
}

console.log(`FishFM sign-in · ${providerName}`);
console.log(`  credential store: ${credentials.kind}${dryRun ? ' (nothing will be kept)' : ` at ${stateDirectory}`}`);
if (!dryRun && process.platform !== 'win32') {
  console.log('  note: DPAPI is Windows-only; on other platforms use --dry-run for now');
}

// --- 1. ask for a QR ---------------------------------------------------------

let qr;
try {
  qr = await provider.beginLogin();
} catch (error) {
  fail(`could not start sign-in: ${error.message}`,
    error.code === 'endpoint_unconfigured'
      ? 'this build has no endpoint profile for that role'
      : 'the endpoint profile is unverified: see docs/spikes/P0-02-netease.md');
}

if (!qr?.key) {
  fail('the platform did not return a sign-in key',
    `response shape was ${describeShape(qr)} — record it in docs/spikes/P0-02-netease.md and correct the profile`);
}
console.log(`\n1. sign-in key received: ${String(qr.key).slice(0, 8)}…`);

// The QR image is generated by the platform, so no local QR encoder is needed.
let imagePath = null;
try {
  const image = await transport.request({ role: 'qrImage', params: { key: qr.key } });
  const candidate = image?.body?.data?.qrimg ?? image?.body?.qrimg ?? null;
  if (typeof candidate === 'string' && candidate.length > 100) {
    const base64 = candidate.replace(/^data:image\/\w+;base64,/, '');
    mkdirSync(stateDirectory, { recursive: true });
    imagePath = join(stateDirectory, `login-${providerName}.png`);
    writeFileSync(imagePath, Buffer.from(base64, 'base64'));
    console.log(`2. QR image written to ${imagePath}`);
  } else {
    console.log(`2. the platform returned no QR image (shape ${describeShape(image?.body)})`);
  }
} catch (error) {
  console.log(`2. QR image request failed: ${error.message}`);
}

if (imagePath) {
  // Opening the image is the user's action, not a hidden one.
  if (hasFlag('--open') || process.platform === 'win32') {
    try {
      const child = spawn('powershell.exe', ['-NoProfile', '-Command', `Invoke-Item -LiteralPath '${imagePath.replace(/'/g, "''")}'`],
        { detached: true, stdio: 'ignore', windowsHide: true });
      child.unref();
      console.log('   opened it in your default image viewer — scan it with the phone app');
    } catch { /* opening is a convenience, not a requirement */ }
  }
} else if (qr.qrUrl) {
  console.log(`   platform supplied a sign-in URL: ${qr.qrUrl}`);
} else {
  console.log('   no QR image was produced. Re-run and read the line above to fix the profile.');
}

if (!existsSync(stateDirectory)) mkdirSync(stateDirectory, { recursive: true });
if (qr.qrUrl) writeFileSync(join(stateDirectory, `login-${providerName}.txt`), `${qr.qrUrl}\n`, 'utf8');

// --- 2. poll until confirmed -------------------------------------------------

console.log(`\n3. waiting for confirmation (up to ${timeoutSeconds}s, polling every 3s)…`);
const deadline = Date.now() + timeoutSeconds * 1000;
let status = 'waiting';
let checked = 0;
while (Date.now() < deadline) {
  await new Promise((resolve) => setTimeout(resolve, 3000));
  checked += 1;
  let polled;
  try {
    polled = await provider.pollLogin();
  } catch (error) {
    fail(`polling failed: ${error.message}`, 'the loginPoll endpoint profile may be wrong');
  }
  status = polled.status;
  if (status === 'scanned') console.log('   …scanned, confirm on your phone');
  else if (status !== 'waiting' && status !== 'scanned') console.log(`   …${status}`);
  if (status === 'authorized') break;
  if (status === 'expired') {
    fail('the sign-in QR expired before it was confirmed', 'run the command again to get a fresh code');
  }
  if (checked % 10 === 0) console.log(`   …still waiting (${checked} checks)`);
}

if (status !== 'authorized') fail(`gave up after ${timeoutSeconds}s`, 'run the command again when you are ready to scan');

// --- 3. confirm what we stored ----------------------------------------------

const account = provider.getAccount();
console.log(`\n4. signed in. account state: ${account.status}${account.accountId ? ` (id ${account.accountId})` : ''}`);
const described = credentials.describe(reference);
console.log(`   credential: ${described.present ? `stored, ${described.cipherBytes} base64 chars of ciphertext` : 'NOT stored'}`);
if (described.path) console.log(`   file: ${described.path}`);
console.log('   the session itself was never printed and is not in the database');

if (probe) {
  console.log('\n5. probing the account endpoint to confirm the profile…');
  try {
    const restored = await provider.restore();
    console.log(`   account endpoint says: ${restored.status}${restored.accountId ? ` (id ${restored.accountId})` : ''}`);
  } catch (error) {
    console.log(`   account probe failed: ${error.code ?? 'error'} — ${error.message}`);
    console.log('   this is the first thing to correct in docs/spikes/P0-02-netease.md');
  }
}

console.log(`\n${NETEASE_ENDPOINT_PROVENANCE.confirmed.length === 0
  ? 'Reminder: every endpoint in this build is an unconfirmed hypothesis.'
  : 'Some endpoints are confirmed.'} Record what worked in docs/spikes/P0-02-netease.md.`);
console.log(dryRun ? 'Dry run: nothing was persisted.' : 'Session stored. The plugin can now import and play.');